### ISSUE TITLE
ENH: quantile vs equal interval bins

### ISSUE THREAD

**Issue by luca-s** [quantopian/alphalens#105]
While using quantiles is the most straightforward choice there are use cases where it would be much more reasonable to classify the factor values using equal interval bins.

An example is a common scenario where a factor produces positive and negative values (e.g.  in -1, 1 range) and alphalens should be able to calculate statistics on two distinct group: the positive values  group and the negative values one. Currently this is not possible if the positive and negative values are not equally balanced (50% of positive values and 50% of negative values).

So I am proposing to have two way of classifying the factor values:
 - Quantiles (current implementation): this method classifies factor values into a certain number of categories with an equal number of units in each category. This produces bins with the same amount of elements but with different values ranges. 
- Equal Interval bins: the range of factor values is divided equally into however many categories have been chosen (.e.g. range -1,1 and 2 categories would result in one category in the range -1,0 and a second category in the range 0,1).  This second option would produce bins with varying number of elements, but with the same values span.

**Comment by twiecki** [comment]
That makes sense to me. Have you thought about how the API would look like?

**Comment by luca-s** [comment]
My idea would be to add a flag to create_factor_tear_sheet so that the user can supply the binning type (quantile or equal interval). We don't need any other api changes but we need a function similar to performance.quantize_factor that accepts the same input but returns the factor binned by value intervals instead of quantiles. We then call performance.quantize_factor or the new function depending on the binning type flag.

**Comment by twiecki** [comment]
Yes, a kwarg for the binning type makes sense.

**Comment by luca-s** [comment]
I thought about the api change again and an option would be to remove the "quantiles=5"  argument from create_factor_tear_sheet function and add this new argument: 

"binning_mode=(mode, mode_args)"

E.g.:
binning_mode=("quantiles",  5)  #Number of uniform quantiles
binning_mode=("quantiles",   [0, .15, .5, .85, 1.] ) # list of non uniform quantiles
binning_mode=("bins",  5) #number of equal-width bins
binning_mode=("bins",  [-1, -0.3, 0., 0.3, 1] ) # list of bin edges allowing for non-uniform bin width

Also there is room for future addition of new modes.

Note: when "quantiles" mode is selected we'll end up calling pandas.qcut and when "bins" is provided we'll call pandas.cut

**Comment by twiecki** [comment]
That looks a bit bloated to me. What if we just have quantiles and bins and only one of them can be not-None?

**Comment by luca-s** [comment]
That sounds good too, let's go for that then.
