### ISSUE TITLE
Make certain plots default to not display

### ISSUE THREAD

**Issue by twiecki** [quantopian/alphalens#106]
Tear-sheet is a bit overloaded currently.

**Comment by jameschristopher** [comment]
totally, I could also see breaking the `create_factor_tear_sheet` into 

- `create_full_tear_sheet`
- `create_summary_tear_sheet`
- `create_returns_tear_sheet`
- `create_information_tear_sheet`
- `create_turnover_tear_sheet`

**Comment by twiecki** [comment]
Yes, that's probably a good idea.

**Comment by jameschristopher** [comment]
fixed https://github.com/quantopian/alphalens/pull/130
