### ISSUE TITLE
Cumulative quantile return plot is not meaningful

### ISSUE THREAD

**Issue by twiecki** [quantopian/alphalens#107]
@luca-s the plots `plot_quantile_cumulative_avg_return` do not seem to make sense, or at least the error bars dominate. Any idea how to improve that?

![image](https://cloud.githubusercontent.com/assets/674200/20565526/2d0b5460-b192-11e6-9d85-52865f11e48a.png)

**Comment by luca-s** [comment]
The error bars represent the standard deviation of the quantile cumulative returns at any period. If the cumulative returns deviate from the mean very much we get what you are seeing. 

I would say that having a small standard deviation is an indication of the quality of the ranking scheme and I believe that weak alphas correspond to plots where the error bars dominate.

As an example, here is the plot for a factor with a higher alpha:

![download](https://cloud.githubusercontent.com/assets/15273575/20572010/fe202672-b1a9-11e6-9d8d-94f87a0bccb5.png)

Anyway, I found a bug in the average cumulative return plot by quantile and I fixed it in #101, so it would be worth running the tearsheet with that patch and compare the results. Also, I will double check that the standard deviation is calculated and plotted correctly and also that it matches the results we get in the violin plot. 

I am open to alternative ways of plotting the standard deviation if you still think that the current method doesn't show this information in the clearest way.

**Comment by luca-s** [comment]
@twiecki I dug into the code and I discovered (If I can say that, I am the one who wrote it in the first place)  the standard deviation is calculated from the cumulative returns **of each asset** (the totality of them, every asset for every day) belonging to the same quantile. Actually I should have first calculated the quantile mean cumulative returns for every "day" (period actually) and then calculate the standard deviation of those "daily" mean returns. In this second case the standard deviation is obviously smaller but it is also  more meaningful.  (I hope my explanation is not too confusing).

If it is fine with you I would submit the fix in the same PR as #101, as I have already made many changes in there regarding this plot (or I can split that PR in two) and this would be just an additional fix.

This is an example of the change in standard deviation bars after the fix:

![download 2](https://cloud.githubusercontent.com/assets/15273575/20591884/181e93b6-b22b-11e6-906d-ba4a657f89e6.png)

**Comment by twiecki** [comment]
Great catch, yeah that PR will work well.

**Comment by luca-s** [comment]
I will submit this additional fix and then you can try and see if it improves your use case.

**Comment by luca-s** [comment]
@twiecki if you still have the original data used for reporting the issue, I would be curious to see how the plots look like now that many bugs have been fixed.
