### ISSUE TITLE
10 Day IC looks like downsampled 1 day IC in rolling plots

### ISSUE THREAD

**Issue by CaptainKanuk** [quantopian/alphalens#109]
In the rolling IC plots the longer timeframes look like downsampled versions of the shorter ones. Can we get a code correctness check on those plots and make sure that they're behaving as expected?

**Comment by twiecki** [comment]
CC @luca-s

**Comment by luca-s** [comment]
@twiecki Out of curiosity I had a look but I didn't see any obvious reason that explains a downsampling. @CaptainKanuk would it be possible to have a screenshot of the plots that raised the doubts?

**Comment by CaptainKanuk** [comment]
These are the plots that invited suspicion. It could just be a coincidence with the factor, if the code looks good I won't worry about it. 
![screen shot 2016-12-02 at 12 59 01 pm](https://cloud.githubusercontent.com/assets/3255615/20844727/3b8544ac-b88f-11e6-8eee-b3994accb34d.png)
