### ISSUE TITLE
quantile_calc with equal weight factor

### ISSUE THREAD

**Issue by xsavenberg** [quantopian/alphalens#114]
The `quantile_calc` function in performance.py crashes when you provide it with exact equally weighted factors, as the bin edges are not considered unique. 

    def quantile_calc(x, quantiles):
        return pd.qcut(x, quantiles, labels=False) + 1

should become 

    def quantile_calc(x, quantiles):
        return pd.qcut(x.rank(method='first'), quantiles, labels=False) + 1

since the ranking function will make the qcut understand some type of uniqueness between the bins, and therefore just make the cut where it wants to.

**Comment by luca-s** [comment]
That has been discussed here #104  but rejected.  Would issue #113 fix your use case?

**Comment by xsavenberg** [comment]
Sorry, I missed that one. 
I agree with the reasoning there, and could work with the solution proposed in #113 .
This can be closed.
