### ISSUE TITLE
Comparative tear sheet

### ISSUE THREAD

**Issue by xsavenberg** [quantopian/alphalens#120]
Would it be an idea to build a tear-sheet that holds two return streams (the current and next iteration of an alpha for example) against the same light?

**Comment by twiecki** [comment]
Yes, I think that would be very neat.

**Comment by luca-s** [comment]
What kind of comparison would you imagine to see? That is, what plots would be affected? and in which way?

Currently I compare lots of different factors and to do it I simply save the plots to file and then I compare the saved images, much better than having them on the Notebooks (but then it depends on what program you use to view the images).

**Comment by xsavenberg** [comment]
I would imagine this as putting for example a plot of both cumulative returns along with A-B to see the spread created in the new iteration of a model? The same approach could be applied to rolling sharpe, rolling IC, etc. 

That way when comparing two alphas, you can more easily identify exactly where and by how much they differ.

**Comment by luca-s** [comment]
It seems reasonable but we have to look plot by plot and see if it makes sense to create a comparative version for each of them and how to make the comparison. Some of the plots might become difficult to read  if we put too much overlapping data on them.

**Comment by twiecki** [comment]
I think it should be possible to just pass in the same axes object twice and create comparisons that way. I don't think it's something we should add explicit support for.

**Comment by xsavenberg** [comment]
makes sense, it was just a "thinking out loud" type of question :) 
this can be closed in that case
