### ISSUE TITLE
Yellow colour is hard to see on cumulative returns by quantile plots.

### ISSUE THREAD

**Issue by jmccorriston** [quantopian/alphalens#124]
![image](https://cloud.githubusercontent.com/assets/4500507/21773567/99904e02-d65d-11e6-8ef2-06e823265c0c.png)

I didn't even see the lines for Quantile 2!

**Comment by DMTSource** [comment]
I came to post the same issue but I just noticed on the front page for this repo there is a nice gray bg color for each subplot. These are not shown here(or in my Research notebook on Quantopian) when generating a tearsheet. The code in plotting.py seems to be setting the colors via the rc defaults(line 85).

Perhaps the yellow can stay to retain color variety for higher number of quantiles(assuming this was part of the intent cause there are only so many differentiable colors in mpl) and the bg color can be re-addressed?

**Comment by luca-s** [comment]
I agree with @DMTSource that making the background dark would solve the problem. 

By the way, I believe we should use seaborn.axes_style() to change the background colour, while the current code uses seaborn.plotting_context() that is intended to control the **scale** of plot elements.

**Comment by luca-s** [comment]
Fixed in #125, I am closing this. Feel free to re-open it if required
