### ISSUE TITLE
groupby_labels show unreadable block if use chinese 

### ISSUE THREAD

**Issue by wukan1986** [quantopian/alphalens#133]
If we want to show **chinese** right, we must use this code 

```
plt.rcParams['font.family'] = 'SimHei'
plt.rcParams['axes.unicode_minus']=False
```

but when print(plt.rcParams) in tears.py, i found it not work.

so i try to fix it.

```
import alphalens

import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'SimHei'
plt.rcParams['axes.unicode_minus']=False

alphalens_tears.create_factor_tear_sheet(momentum_factor, pricing, groupby=ticker_sector,
                                         groupby_labels=sector_names, turnover_for_all_periods=True,
                                         rcParams=plt.rcParams)
```

```
@plotting.customize
def create_factor_tear_sheet(factor,
                             prices,
                             groupby=None,
                             show_groupby_plots=True,
                             periods=(1, 5, 10),
                             quantiles=5,
                             bins=None,
                             filter_zscore=10,
                             groupby_labels=None,
                             long_short=True,
                             avgretplot=(5, 15),
                             turnover_for_all_periods=False,
                             rcParams=None):
```

```
# Returns
fr_cols = len(periods)
vertical_sections = 2 + fr_cols * 3

if rcParams is not None:
	plt.rcParams = rcParams

gf = GridFigure(rows=vertical_sections, cols=1)
```

**Comment by luca-s** [comment]
The matplotlib setting are created with [plotting.customize](https://github.com/quantopian/alphalens/blob/master/alphalens/plotting.py#L33) function that is a decorator for all the [tear sheet functions](https://github.com/quantopian/alphalens/blob/master/alphalens/tears.py#L324). See [seaborn documentation](http://seaborn.pydata.org/tutorial/aesthetics.html) to understand how it works.

So, in order to add your custom matplotlib settings you should re-implement plotting.customize because we don't provide a way to pass custom settings to it, at the moment. A possible (ugly) workaround would be to run this at the beginning of your NB (and only once):

```
from alphalens import plotting
axes_style = plotting.axes_style

def __axes_style(style='darkgrid', rc=None):   
    # add your custom settings, but please note that not all matplotlib settings
    # are available, for example 'axes.unicode_minus'
    # see http://seaborn.pydata.org/tutorial/aesthetics.html for details
    my_rc = {'font.family' : 'SimHei'} 
    return axes_style('whitegrid', my_rc)
    
plotting.axes_style = __axes_style
```

Let me know if this helps

**Comment by twiecki** [comment]
You should be able to set your own plotting context easily: https://github.com/quantopian/alphalens/blob/master/alphalens/plotting.py#L71

**Comment by luca-s** [comment]
@twiecki that won't work becuase [plotting.customize](https://github.com/quantopian/alphalens/blob/master/alphalens/plotting.py#L33) decorator will overwrite any previous settings

**Comment by luca-s** [comment]
@twiecki actually it works, I forgot that we have to add the `set_context=False` argument to prevent alpahlens from applying its matplotlib settings , e.g.

```
rc1= { ... }  # custom plotting_context settings
rc2= { ... }  # custom axes_style settings
with alphalens.plotting.plotting_context(rc=rc1), alphalens.plotting.axes_style(rc=rc2):
      alphalens.tears.create_event_returns_tear_sheet(...,  set_context=False)
```

**Comment by wukan1986** [comment]
It works!Thank you very much!
