### ISSUE TITLE
Is alphalens on PyPi ?

### ISSUE THREAD

**Issue by HintikkaKimmo** [quantopian/alphalens#134]
I am getting an error below, and a quick search on PYPI website did not find alphalens.

```
(finance-env)➜  Finance pip install alphalens
Collecting alphalens
  Could not find a version that satisfies the requirement alphalens (from versions: )
No matching distribution found for alphalens.
```

Python versions tried 2.7.13 and 3.60 

Python 2.7.13 (default, Dec 19 2016, 08:09:44) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

I installed alphalens successfully directly from Github `(finance-env)➜  Finance pip install git+https://github.com/quantopian/alphalens`

**Comment by twiecki** [comment]
It's not on pypi yet but should be soon. In the mean-time you can install:
`pip install git+https://github.com/quantopian/alphalens`

**Comment by twiecki** [comment]
Dup of https://github.com/quantopian/alphalens/issues/29.
