### ISSUE TITLE
Can I save the images of the result into some file(jpg, pdf) using code instead of saving image in ipython notebook? 

### ISSUE THREAD

**Issue by huaiweicheng** [quantopian/alphalens#138]

**Comment by luca-s** [comment]
I don't believe you can save the plots via code at the moment, because we don't return the plot `Figures` from the tear sheet function. Though you can right clink on the image and "save as..." them instead of saving the full NB.

@twiecki, @jameschristopher  should we consider returning the `Figures` from the top level tear sheet api?

**Comment by twiecki** [comment]
Can't you get the figure via ax.figure? Thus, ax.figure.save() should work.

**Comment by jameschristopher** [comment]
Another thing to note is that ipython let's you export a notebook into many formats from its UI

**Comment by huaiweicheng** [comment]
@luca-s  @jameschristopher
What I really need is that to produce the image periodically without sharing the code to other people.( I do not want other guys seeing the factor I use) 
 I know that you can get the image in two ways: 
1. Save as in the ipython notebook
2. nbconvert to pdf
However, Method 1 need persons to get image from html automatically(similar to network crawler)
Method 2 you can not hide the code.

@twiecki 
Is that a way I can use alphalens in python project without ipython notebook? since I have no idea how to implement this feature(periodically, hiding code) in ipython notebook.

**Comment by twiecki** [comment]
@huaiweicheng Yes.

**Comment by huaiweicheng** [comment]
@twiecki  Thanks a lot. I will try. Good day.

**Comment by stanleywu111** [comment]
```python
from matplotlib.backends.backend_pdf import PdfPages

mean_return_by_q_daily, std_err = alphalens.performance.mean_return_by_quantile(factor_data, by_date=True)
mean_return_by_q, std_err_by_q = alphalens.performance.mean_return_by_quantile(factor_data, by_group=False)
plot1 = alphalens.plotting.plot_quantile_returns_bar(mean_return_by_q)
plot2 = alphalens.plotting.plot_quantile_returns_violin(mean_return_by_q_daily)
plot3 = alphalens.plotting.plot_cumulative_returns_by_quantile(mean_return_by_q_daily)

with PdfPages('results/multipage_pdf.pdf') as pdf:
    pdf.savefig(plot1.figure)
    pdf.savefig(plot2.figure)
    pdf.savefig(plot3.figure)
```

**Comment by luca-s** [comment]
I am closing this issue
