### ISSUE TITLE
Seems unable to install on windows 7

### ISSUE THREAD

**Issue by tesla1060** [quantopian/alphalens#139]
Hi,
I am using win7 64bit. By using `pip install alphalens`, I received error:  `Could not find a version that satisfies the requirement alphalens (from versions: ) No matching distribution found for alphalens`

**Comment by luca-s** [comment]
It's not on pypi yet. In the mean-time you can install:
pip install git+https://github.com/quantopian/alphalens

See #29, when completed you will find Alphalens on pypi
