### ISSUE TITLE
 AttributeError: 'Index' object has no attribute 'tz..,probably because our research stock market is in China  

### ISSUE THREAD

**Issue by EYcab** [quantopian/alphalens#145]
Please help with handling this error,I did every other thing fine but the tz as I trace along:
  if factor.index.get_level_values('date').tz != prices.index.tz:
        raise NonMatchingTimezoneError("The timezone of 'factor' is not the "
                                       "same as the timezone of 'prices'. See "
                                       "the pandas method tz_localize.")
Any clue at all?

**Comment by timinGo** [comment]
same problem

**Comment by Leona0616** [comment]
You need to set the column 'data' to index.
Here is what I have done to resolve the same problem.


import pytz
from pytz import timezone

dataset['PeriodEnd'] = pd.to_datetime(dataset['PeriodEnd'])
dataset.set_index('PeriodEnd', drop = False, inplace = True)
Mt_Gambier= timezone('Australia/Adelaide')
dataset.index = dataset.index.tz_localize('UTC').tz_convert(Mt_Gambier)
dataset.head()

You will get the result you want.

**Comment by BinhKieu82** [comment]
Hi Leona0616 , 
I've tried following up your guidance but not successful yet. My case the first dataset is multiindex, `levels[0]` is date in `dtype='object', length=506)` format, `levels[1]` is `tickers' name`, meanwhile the second dataset is single index, the date in `dtype='datetime64[ns, UTC]', length=506, freq='C'` format.
Could you give a hand for that please!
With thanks

**Comment by BinhKieu82** [comment]
Here is my case of 2 levels pandas index dataframe. Level[0] is datetime, level[1] is ticker. 
dataset.index = dataset.index.set_levels([pd.to_datetime(dataset.index.levels[0]).tz_localize('UTC'),dataset.index.levels[1]])
Hope that helps

**Comment by jmrichardson** [comment]
prices should not have a multi index.  You need to unstack into wide format, for example:

prices.open.unstack(level=1)

**Comment by fomalhaut11** [comment]
> Hi Leona0616 , I've tried following up your guidance but not successful yet. My case the first dataset is multiindex, `levels[0]` is date in `dtype='object', length=506)` format, `levels[1]` is `tickers' name`, meanwhile the second dataset is single index, the date in `dtype='datetime64[ns, UTC]', length=506, freq='C'` format. Could you give a hand for that please! With thanks

have you solved that problem?i meet the same issue

**Comment by JaggerH** [comment]
For anybody who get into this problem, this is how I resolve the problem.
##  Factor DF
```
			market_cap	pe_ratio	total_operating_revenue
date	code				
2019-01-02	000001.XSHE	1577.9608	6.4428	2.942300e+10
2019-01-03	000001.XSHE	1593.4142	6.5059	2.942300e+10
2019-01-04	000001.XSHE	1674.1151	6.7456	2.942300e+10
2019-01-07	000001.XSHE	1672.3981	6.7386	2.942300e+10
2019-01-08	000001.XSHE	1658.6617	6.6833	2.942300e+10
```
## Price DF
![image](https://github.com/quantopian/alphalens/assets/5411606/cec35c94-ef10-4d3a-9965-b6cfe024a7cb)
### how I got price df
```python
price = get_price(stocks_set, '2019-01-01', '2020-01-01')
price = price.close
price.index.name = 'date'
price.columns.name = 'code'
price.head()
```
## How to fix
```python
#  factor df
series_facs_datas.index = series_facs_datas.index.set_levels([pd.to_datetime(series_facs_datas.index.levels[0]).tz_localize('UTC'),series_facs_datas.index.levels[1]])

# tick
price.index = pd.to_datetime(price.index).tz_localize('UTC')
```
