### ISSUE TITLE
perf.factor_alpha_beta doc string typo

### ISSUE THREAD

**Issue by MichaelJMath** [quantopian/alphalens#156]
I believe there is a mistake in the docstring for **perf.factor_alpha_beta**.

Current doc string:
    
Computes the alpha (excess returns), alpha t-stat (alpha significance),
    and beta (market exposure) of a factor. A regression is run with
    the period wise factor universe mean return as the dependent variable
    and mean period wise return from a dollar-neutral portfolio weighted
    by factor values as the independent variable.

My recommendation (switch dependent and independent variable):
    
Computes the alpha (excess returns), alpha t-stat (alpha significance),
    and beta (market exposure) of a factor. A regression is run with
    the period wise factor universe mean return as the independent variable
    and mean period wise return from a dollar-neutral portfolio weighted
    by factor values as the dependent variable.

**Comment by luca-s** [comment]
I agree with you. Are you interested in providing a PR?
