### ISSUE TITLE
Trade at the Close vs Trade at the Open

### ISSUE THREAD

**Issue by marketneutral** [quantopian/alphalens#165]
The common workflow for `alphalens` as described [here](https://www.quantopian.com/lectures/factor-analysis) is

- take a `results` dataframe as output from `run_pipeline`
- get pricing as

```
assets = results.index.levels[1]
pricing = get_pricing(
    assets,
    pd.Timestamp(start),
    pd.Timestamp(end) + pd.Timedelta(days=30),
    fields="open_price"
)
```

- combine the `results` and `pricing` dataframes as

```
factor_data[factor] = al.utils.get_clean_factor_and_forward_returns(
    factor=results[factor],
    prices=pricing,
    periods=[1]
)
```
- perform whatever analysis you like, e.g.,
```
ls = al.performance.factor_returns(factor_data[factor])
```

This workflow (rightly) pre-supposes that the "information" arrives prior to the market open and the first opportunity to capture that information is by trading benchmarked to the market open.

However, when working with, for example, a factor based purely on price and volume data, it might be desirable to analyze the factor against the contemporaneous closing price, **not against the next day's open price**. To give a concrete example, if I have a daily mean-reversion factor that uses the close price on day `t` to generate a signal, I want to measure it **assuming execution at the close price on** `t`. The spirit of what I am hoping to analyze is: in real production trading, one might generate the signal at 3:50pm and trade benchmarked to the 4pm close price. Forgetting any arguments as to the philosophical reasons why one should not do this for analysis or whether it is practical to do in production trading please, my question is:

What is the most elegant way to modify the above workflow to use the close_price for `t` for the `alphalens` studies? Noting the obvious that simply changing `fields="open_price"` to `fields="close_price` would result in `alphalens` studies versus the `t+1` close price, not the `t` close price.

In the industry, this would be called a "delay 0" alpha, versus the workflow above which would be called a "delay 1" alpha.

**Comment by twiecki** [comment]
@luca-s any idea?

**Comment by luca-s** [comment]
@marketneutral  my idea would be to change `fields="open_price"` to ` fields="close_price"` in `get_pricing` AND to create the factor DataFrame (`result` in your example) manually. That means you could use Pipeline to produce the daily securities universe but not the values, those should be calculated in another way (probably calling `get_pricing` in minute mode) using the information available before the close price of each day.

If you have a concrete example to work with I will be interested to make sure Alphalens can properly work on that.

**Comment by marketneutral** [comment]
Thanks @luca-s. I would like to continue to use pipeline and not have to code the cross-sectional strategy on a cut of minutely data (I realize of course if I wanted to do this in production trading, I would in fact have to do this, but at this stage I am just trying to validate a signal and iterate on its construction). One thing I thought of is to to change `fields="open_price"` to `fields="close_price"` in `get_pricing` and shift the pipeline `results` with

```
results = results.unstack().shift(-1).stack()
```

as that aligns the pipeline output with the actual day of the `closing_price`. This however is not right because

- tickers are not consistent over days when using a dynamic universe (e.g., `Q1500US`). As such, a ticker may be in the universe on `t` but not `t+1`; when I shift the signals, I'd get a `NaN` on `t`. For example, spoofing a pipeline results dataframe
```
arrays = [['Mon', 'Mon', 'Mon', 'Tues','Tues','Tues','Wed','Wed'],
          ['ABC', 'XYZ', 'JKL', 'ABC', 'RST', 'JKL','ABC', 'XYZ']]
index = pd.MultiIndex.from_tuples(list(zip(*arrays)))
s = pd.Series(np.random.random(8), index=index)
df = pd.DataFrame(s, columns = ['Signal'])
print df

            Signal
Mon  ABC  0.437987
     XYZ  0.390615
     JKL  0.652820
Tues ABC  0.304480
     RST  0.203087
     JKL  0.134543
Wed  ABC  0.636738
     XYZ  0.886676

print df.unstack()

        Signal                              
           ABC       JKL       RST       XYZ
Mon   0.437987  0.652820       NaN  0.390615
Tues  0.304480  0.134543  0.203087       NaN
Wed   0.636738       NaN       NaN  0.886676

print df.unstack().shift(-1)

        Signal                              
           ABC       JKL       RST       XYZ
Mon   0.304480  0.134543  0.203087       NaN
Tues  0.636738       NaN       NaN  0.886676
Wed        NaN       NaN       NaN       NaN

print df.unstack().shift(-1).stack()

            Signal
Mon  ABC  0.304480
     JKL  0.134543
     RST  0.203087
Tues ABC  0.636738
     XYZ  0.886676

```
In that case, the only ticker treated "properly" is ABC. For example, XYZ was known to the tradeable universe on Monday but not on Tuesday. When I shift the signal back from Tuesday to Monday, I don't have a value.

- because of the prior bullet, this will not preserve operations like `.demean(groupby=...)` calls inside the pipeline

@ssanderson Do you have any ideas on this?

**Comment by luca-s** [comment]
If the daily information calculated by Pipeline is enough for your factor then your idea of shifting the pipeline output back by 1 is fine.

Regarding the problem of the dynamic universe I believe the default frequency at which Q1500US and Q500US recalculate their universes is a month (better double check the implementation/documentation).  If this is the case then the error you might introduce due to a changing universe should be small.

**Comment by luca-s** [comment]
Also, the obvious workaround to the dynamic universe problem is to discard the tickers that were not present the previous day after the 1 day shift. You will lose some tickers of you universe but that shouldn't be a big problem especially if  Q1500US and Q500US recalculate their universes every month.

**Comment by luca-s** [comment]
I did a little test with 1 year of factor data and Q1500US filter:

```
results = run_pipeline(pipe, start_date='2013-01-01', end_date='2014-01-01')
print results.isnull().sum()
```
myfactor    **0**
```
results[:] = results.unstack().shift(-1).stack()
print results.isnull().sum()
```
myfactor    **1783**

```
print results.isnull().sum() / float(len(results))
```
myfactor    **0.004716**

**values lost: 0.47 %**

**Comment by ssanderson** [comment]
I haven't had time to fully digest this thread, and probably won't be able to until I get back from scipy, but a few off-the-cuff notes:

1. It's probably easier to shift the results of `get_pricing` than it is to shift the results of `get_backtest`.
2. Remember that pipeline models a daily computation process that happens in the morning of any given day.  The outputs from a pipeline on day N are the values that would be computed given the information available at roughly 8:45 AM on the morning of day N, which means that, in practice, pipeline's date labelling convention is one day shifted from the convention of `get_pricing`, which labels day N with data that was known as of the end of that day.  Unless alphalens is doing some additional shifting elsewhere, if your goal is to measure the quality of your pipeline alpha labelled with day N, I'd expect the relevant prices for comparison to be the open price for `get_pricing` on day N (which is the price correponding to the next moment you could trade) and the close price for the same (which is the last price on that day that you could trade).
3. It's not clear to me what date-labelling conventions alphalens is expecting in `get_clean_factor_and_forward_returns`.  The docstring for that function says this:

> It is important to pass the correct pricing data in depending on what time of
period your signal was generated so to avoid lookahead bias, or delayed
calculations. Pricing data must span the factor analysis time period plus an
additional buffer window that is greater than the maximum number of expected
periods in the forward returns calculations.

but that doesn't actually explain to a user how they should be aligning their alpha values and their price values. IMO, a much simpler API would be to for alphalens to never work with prices and instead require the user pass in alpha + "values to predict", where the values to predict would be forward returns on different time horizons.

**Comment by luca-s** [comment]
More than Alphalens, this issue is actually on how to compute a factor at market close instead of market open. Alphalens works fine at any time at any time frequency, there are not real issues here.

The source of confusion is that Alphalens has been always explained in bundle with Pipeline, so daily frequency and factor computed at market open. This creates uncertainty on how to make use of Alphalens in other use cases. The lack of NBs in Alphalens examples that cover those other use cases doesn't help and neither does the  unclear documentation, as highlighted by @ssanderson. 

I believe that improvements on the documentation plus some clear explanations/examples on how to align the alpha values and the price values in different scenarios (trade at the open vs trade at the close vs intraday trade) would suffice. 

Regarding @ssanderson  suggestion "alphalens to never work with prices" I can say that has been already covered by a [big API rework](https://github.com/quantopian/alphalens/pull/130) by @jameschristopher . The main tearsheet functions work with forward returns only and get_clean_factor_and_forward_returns is an utility function that helps to build the forward returns from the prices, in case the former are not available. 

Finally, I still  believe the workaround explained above should  work fine for @marketneutral

**Comment by luca-s** [comment]
The function arguments are now documented with meaningful examples. Still missing NB examples of running Alphalens with frequency other than daily data or examples of trading at the close or any other point in time that is not market open.

**Comment by luca-s** [comment]
I am closing this as the API documentation was improved and the example NBs too. Feel free to re-open this is required
