### ISSUE TITLE
Add long_short flag for performance.alpha_beta and modify tearsheet

### ISSUE THREAD

**Issue by MichaelJMath** [quantopian/alphalens#167]
I recommend adding a long_short flag to the **performance.factor_alpha_beta()** function along with associated functionality in the function code. My rationale is that when running **tears.create_full_tear_sheet()** with the long_short flag set to False, the "Returns Analysis" table still shows the alpha and more importantly the beta being calculated by regressing the factor-weighted long-short portfolio vs. the universe mean return, as opposed to the factor-weighted long-only portfolio. vs the universe mean return. 

I can work on this and submit a pull request, but I would appreciate it if someone could look over my rationale and comment as to whether you think this makes sense or not before I make the changes.

**Comment by luca-s** [comment]
oh, that's right. Thank you for reporting this @MichaelJMath . If you submit a PR that would be greatly appreciated.
