### ISSUE TITLE
Alpha decomposition

### ISSUE THREAD

**Issue by eigenfoo** [quantopian/alphalens#180]
As per @marketneutral's suggestion, it would be a fantastic addition to `alphalens` to implement the analysis done in @cfenaroli's [public research lecture](https://github.com/quantopian/research_public/blob/alt-data-case-studies/case_studies/USD_EUR_exchange_rate/notebook.ipynb), inspired by Exhibit 3 in [this AQR whitepaper](https://www.aqr.com/-/media/files/papers/measuring-factor-exposures-uses-and-abuses.pdf). Specifically, we should implement an "alpha decomposition" which looks like this:

![screen shot 2017-08-04 at 4 00 55 pm](https://user-images.githubusercontent.com/19851673/28985007-8bd7ddba-792e-11e7-986c-40119127f20d.png)

To be more precise, given a factor risk model, we would like to see how much of the alpha's returns is explained by common risk factors, such as sector, momentum, etc. This is easily done by finding the algo returns' betas to the common factors through a simple multivariate linear regression. This would allow us to see how much of the alpha's returns is driven by genuine stock-specific reasons, and how much can be attributed to common factors.

**Comment by marketneutral** [comment]
@georgh0021 This would be a fantastic addition to `pyfolio` as well. In fact that would be an easier add since `pyfolio` already takes in the SMB, HML, and UMD factors from Ken French's website and has a rolling plot of exposures.

**Comment by mmargenot** [comment]
This is being covered in https://github.com/quantopian/alphalens/issues/225 in more detail.
