### ISSUE TITLE
Improve docstrings

### ISSUE THREAD

**Issue by eigenfoo** [quantopian/alphalens#181]
There are two main issues with the docstrings as they are:

- [ ] They repeat themselves a lot. There should be one docstring per input per module, and all other functions should reference the "main" docstring. See [this line on `tears.py` on pyfolio](https://github.com/quantopian/pyfolio/blob/master/pyfolio/tears.py#L419) for an example.

- [ ] There aren't any examples. As good as verbose, detailed explanations of inputs are, an example would help illustrate a lot. See [this line on `tears.py` on pyfolio](https://github.com/quantopian/pyfolio/blob/master/pyfolio/tears.py#L104) for an example.

**Comment by luca-s** [comment]
Regarding your second point, I just wanted to highlight that the input to the tears.* funtions is built by [utils.get_clean_factor_and_forward_returns](https://github.com/quantopian/alphalens/blob/master/alphalens/utils.py#216 ). So utils.get_clean_factor_and_forward_returns documentation should be taken into consideration too when dealing with tears.* funtions one

**Comment by luca-s** [comment]
Added all data examples in utils.get_clean_factor_and_forward_returns and added a comment in each tears.* function " See full explanation in utils.get_clean_factor_and_forward_returns"
