### ISSUE TITLE
Can alphalens have pyfolio/zipline as dependencies?

### ISSUE THREAD

**Issue by georgh0021** [quantopian/alphalens#182]
There are certain functions in pyfolio's `utils.py` that would be very useful for alphalens. Specifically, the functions to [load_portfolio_risk_factors](https://github.com/quantopian/pyfolio/blob/master/pyfolio/utils.py#L343) from Dartmouth, and possibly [get_treasury_yield](https://github.com/quantopian/pyfolio/blob/master/pyfolio/utils.py#L374) as a benchmark.

Would it be better to move the needed functions into alphalens' `utils.py`, or to introduce pyfolio as a dependency? Zipline might have useful functions as well. Would it be safe to have alphalens depend on zipline?

Since the "order" of our open source libraries (i.e. the order a quant would use them in the quant workflow) goes: alphalens, zipline, pyfolio, it seems intuitive to me that alphalens should depend on zipline and pyfolio, since it is giving the user a rudimentary, "sneak preview" of backtest results and tear sheet analysis using a quantile long-short portfolio of the alpha... @twiecki @richafrank thoughts?

**Comment by twiecki** [comment]
I'm fine with pyfolio as a dependency but not zipline. Alternatively we
could move more functionality into empyrical.

**Comment by georgh0021** [comment]
I feel as if enhancing empyrical would make more sense, since it's a more stable library with a lesser chance of bringing up compatibility issues. Making pyfolio a dependency makes me a bit uneasy, given how quickly it's being developed and built right now...
