### ISSUE TITLE
How to interpret the cumulative return for N forward period in cumulative factor return plots?

### ISSUE THREAD

**Issue by HereticSK** [quantopian/alphalens#187]
In `plot_cumulative_returns_by_quantile`, cumulative returns for periods more than 1 is computed as:
```Python
 if period > 1:
        ret_wide = pd.rolling_apply(
            ret_wide,
            period,
            # compound returns
            lambda ret, period: ((np.nanmean(ret) + 1)**(1. / period)) - 1,
            min_periods=1,
            args=(period,))

    cum_ret = ret_wide.add(1).cumprod()
```
It converts the N-period return to one-period return by taking geometric mean. But I don't know how to make sense of this "derived" return, because:
- Numerically, this "derived" one-period return is not equal to the exact one-period return computed as Price_t/Price_t-1 - 1. Maybe it can be seen as some kind of approximation, but that requires we make some assumption on the N-period return
- Intuitively, cumulative return should be interpreted as generated by some continuously rebalanced portfolio. For instance, cumulative return using simple one-period returns can be interpreted as if the factor weighted portfolio is rebalanced every period. This is very intuitive. But if the cumulative return is computed using the "derived" one-period returns, the interpretation is not as intuitive.

It seems to me that the concept of cumulative return only applies to one-period returns. It does not make much sense to derive some kind of one-period returns from N-period returns just to compute the cumulative return. How much value does it provide for assessing the factor?

**Comment by luca-s** [comment]
The "derived" one-period return is what is called the one-period rate of return:  the returns the factor quantile would have had every 1-period if it had grown at a steady rate. 

But why does Alphalens computes the 1-period rate of return instead of computing the cumulative returns from a N-periods returns? Alphalens makes an assumption on how the factor should be used, that is how and how often a portfolio should be  rebalanced.

If the factor has the best performance at N periods (N >1) then a naive approach of using that factor would be to rebalance the portfolio every N periods. That would work but also it would make the portfolio performance dependent on the specific starting point. Also, Alphalens statistics are calculated considering the factor performance at each period, but if the factor is traded every N periods (rebalancing every N periods) we cannot expect to achieve the same performance.

So, the cumulative returns computed from N periods returns, are calculated assuming an algorithm that divides the initial capital by N and trade each 1/N sub-capital at subsequent periods and each sub-capital is then rebalanced every N periods. This means the algorithm would trade every period (one of the sub-capitals need to be rebalanced  every period) instead of every N-periods and this would mimic the cumulative returns you can see on Alphalens. Also, this kind of approach would produce lower volatility, better leverage/exposure control than an algorithm that rebalanced every N periods

**Comment by luca-s** [comment]
feel free to reopen this if required

**Comment by luca-s** [comment]
Copy-pasting @HereticSK comment here:

> If we are to mimic the cumulative return for the algorithm that holding N equal weighted sub-portfolios and rebalancing them every N period, I wonder if it would make more sense to compute the one-period return as np.nanmean((1 + ret) ** (1. / period) - 1)?
> 
> Compared to the original algorithm, it computes geometric mean before arithmetic mean. For a given period, the one-period return for the whole portfolio equals the average of one-period returns for N sub-portfolios. On the other hand, assuming each sub-portfolio grows at a steady rate within each rebalancing cycle, the one-period return for each sub-portfolio is given by the geometric mean of the corresponding N-period return, i.e. (1 + ret)**(1. / period) - 1). Combining these two steps, gives the one-period return of the whole portfolio equals np.nanmean((1 + ret) ** (1. / period) - 1).
> 
> Moreover, in the original algorithm, ((np.nanmean(ret) + 1) ** (1. / period)) - 1, the N-period returns for each sub-portfolio is averaged first. Somehow that seems like all these N-period returns are realized at this particular period, while they are actually realized at subsequent N periods. So I think it would make more sense to first compute (1 + ret) ** (1. / period) - 1), as an estimation of the realized return for a sub-portfolio on the given period, and then to average over all the sub-portfolios.

**Comment by luca-s** [comment]
@HereticSK 

> For a given period, the one-period return for the whole portfolio equals the average of one-period returns for N sub-portfolios

if you average the sub-portfolios one-period returns you end up with a small error that in a cumulative returns might scale up and become a big error.

```
period = 24

# we have 3 sub-portofolios with the following returns after 8 periods
r1 = 0.05 
r2 = 0.03
r3 = -0.05

portfolio_returns = (r1 + r2 + r3) / 3.

one_period_returns = lambda period, n_periods_returns: (n_periods_returns+1.)**(1./period) - 1

# compute one period returns for the full portfolio
oneP_portfolio = one_period_returns(period, portfolio_returns)

# compute one period returns for each sub portfolio
oneP_r1 = one_period_returns(period, r1)
oneP_r2 = one_period_returns(period, r2)
oneP_r3 = one_period_returns(period, r3)
oneP_avg = (oneP_r1 + oneP_r2 + oneP_r3) / 3.

print "full_portfolio_returns", portfolio_returns
print "returns after",period ,"periods of oneP_portfolio", (oneP_portfolio+1)**period
print "returns after",period ,"periods of oneP_avg", (oneP_avg+1)**period`

```

```
full_portfolio_returns 0.01
returns after 24 periods of oneP_portfolio 1.01
returns after 24 periods of oneP_avg 1.00909886334
```

**Comment by HereticSK** [comment]
@luca-s 
>`portfolo_returns = (r1 + r2 + r3) / 3.` 
If I understand correctly, that means r1, r2, r3 are realized at the same time. That is, all these three sub-portfolios are simultaneously bought 24 periods ago and sold at the same period. This is not consistent with "having N algorithms each rebalancing every N periods".

Under an algorithm holding N sub-portfolios and reblancing every N periods, for a given period, only one of the N sub-portfolios is rebalanced, whose N-period return is realized, while others are not realized until they are rebalanced. In other words, for a given period, each of the past N-period return corresponds to a different time span. I don't know if it is appropriate to average over them.

In terms of the code, each element of `ret` corresponds to a different interval, for instance, ret[1] corresponds to periods from 1 to 3, ret[2] corresponds to periods from 2 to 4......
```Python
 lambda ret, period: ((np.nanmean(ret) + 1)**(1. / period)) - 1,
```
I do agree that there is an error between `oneP_portfolio` and `oneP_avg`. But I think only things like `oneP_r1, oneP_r2, oneP_r3` can be addable since they can be seen as realized at the same time, while `r1, r2, r3` may not be directly addable because they are not simultaneously realized and covers different time interval, not, at least, without some additional assumption.

**Comment by luca-s** [comment]
I understand your doubt about the sub-portofolios not rebalancing the same period, but I believe the current implementation is correct. The rate of returns of the averaged portfolio is computed inside `pd.rolling_apply` for every single period, so every period the set of N-periods return (each one corresponding to a specific sub-portfolio) over which the mean is computed changes: a new N-periods returns exit and a new one enter in the set. Still, each N-periods returns is considered N times.

I suggest to test the current behaviour in this way: run current implementation of `plot_cumulative_returns_by_quantile`  and a new one where the sub-portfolios cumulative returns are computed separately and averaged at the end. The two different implementations have to generate the same results.

**Comment by luca-s** [comment]
@HereticSK I thought again about the way the sub-portfolios are averaged together and you might be right, it could be incorrect if they don't rebalance the same period and they are started in subsequent periods like it happens in Alphalens. I will have to double check and in case it is wrong we can simply compute the sub-portfolios cumulative returns separately and average them at the end.

Please, let me know if you come up with a different idea/conclusion.

**Comment by HereticSK** [comment]
@luca-s Even though sub-portfolios are averaged on a rolling basis, each N-periods return within the rolling window still corresponds to different time spans. It does not seem to make sense to average returns that do not cover the same time span.

>in case it is wrong we can simply compute the sub-portfolios cumulative returns separately and average them at the end.
If I understand correctly, this implementation can only give a cumulative return series of a lower frequency, since the cumulative returns are constructed from N-period returns, which should be a time series of frequency N. If we want to have a cumulative return series of the same frequency as the original N-period return series, we may have to make some assumption in order to recover the one-period returns from the N-period returns. Is that correct?

**Comment by luca-s** [comment]
>  If we want to have a cumulative return series of the same frequency as the original N-period return series, we may have to make some assumption in order to recover the one-period returns from the N-period returns. Is that correct?

Yes and we do it computing the 1-period rate of return for each N-periods return, so that we end up with N sub-portfolio cumulative returns time series if frequency 1 period. Then we can average them.

This is very similar to the current behaviour except now Alphalens averages the N-periods first and then  computes the 1 period rate of returns.

**Comment by HereticSK** [comment]
👍 I see. That's a nice solution.

**Comment by luca-s** [comment]
Suppose you have 2 portfolios with returns 90% and -80% after 60 periods. If you want to simulate the cumulative returns of 1 period you have to compute the rate of returns.

```
def one_period_returns_series(period, returns):
     daily_returns = (returns+1.)**(1./period) - 1
     return pd.Series([daily_returns] * period)

period = 60

s1 = one_period_returns_series(period, returns=0.90)
s2 = one_period_returns_series(period, returns=-0.80)
s1cr = s1.add(1).cumprod()
s2cr = s2.add(1).cumprod()

s1cr.name = 's1cr'
s2cr.name = 's2cr'
s1cr.plot(legend=True)
s2cr.plot(legend=True)
```

![image](https://user-images.githubusercontent.com/15273575/30751727-68b3411e-9fba-11e7-944d-7947afc774c4.png)

Then, if you like to plot the full portfolio cumulative returns you have 2 ways (avgcr1 and avgcr3):


```
# average the 1 period comulative return time series
avgcr1 = (s1cr+s2cr)/2 

# compute the final portfolio returns and build the 1 period rate of returns from that
s12_avg = (0.90-0.80) / 2.
avgcr3 = one_period_returns_series(period, s12_avg).add(1).cumprod()

avgcr2 = ((s1+s2)/2).add(1).cumprod() # this is completely wrong

avgcr1.name = 'avgcr1'
avgcr3.name = 'avgcr3'
s1cr.plot(legend=True)
s2cr.plot(legend=True)
avgcr1.plot(legend=True)
avgcr3.plot(legend=True)
```
![image](https://user-images.githubusercontent.com/15273575/30751873-fa8d8f18-9fba-11e7-88e8-9798641d1283.png)

They are slightly different, but both final values equal the value of the portfolio at the end of the 60 periods. The intermediate values are approximation so you might prefer one or the other.

Alphalens uses the avgcr3 approach and it applies it at every periods, using a rolling window of N-periods returns as input. Here is where the bug might be: compared to the example above, the N-portfolios are shifted by 1 period from each other so the cumulative returns build from that could be slightly wrong, I need to double check. The other approach, avgcr1,  is fine anyway.
