### ISSUE TITLE
Add a util funtion to construct factor_data with pre-computed forward returns dataframe

### ISSUE THREAD

**Issue by HereticSK** [quantopian/alphalens#199]
In `get_clean_factor_and_forward_returns`, the step for computing forward returns `merged_data = compute_forward_returns(prices, periods, filter_zscore)` takes a large proportion of time.

In my opinion, it is rather common to change the factor column, while keeping the forward return columns unchanged, as we want to test different kinds of factors on the same set of forward returns. Currently, the user has to do this by passing a new factor series and rerunning `get_clean_factor_and_forward_returns`. This process can be painfully slow as the pricing data increases.

Is it a good idea to add some functions to allow users to construct factor_data with a pre-computed forward returns dataframe and a factor series? I think this would be more flexible, while the current `get_clean_factor_and_forward_returns` does not have to change. Alternatively, is there any way to make 
`compute_forward_returns` faster?

Attached is a profile of running `get_clean_factor_and_forward_returns`, where the pricing data has a shape of (2295, 3379), and the factor series has a length about 4.8 million.

<html><head><link rel="stylesheet" href="/static/css/notebook.css" type="text/css"><title>Jupyter Pager</title></head><body style="overflow: scroll;"><div id="pager-contents">
        <div id="pager-container" class="container"><pre>Timer unit: 2.85102e-07 s

Total time: 74.7463 s
File: D:\Anaconda3\envs\py35\lib\site-packages\alphalens\utils.py
Function: get_clean_factor_and_forward_returns at line 218

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   218                                           def get_clean_factor_and_forward_returns(factor,
   219                                                                                    prices,
   220                                                                                    groupby=None,
   221                                                                                    by_group=False,
   222                                                                                    quantiles=5,
   223                                                                                    bins=None,
   224                                                                                    periods=(1, 5, 10),
   225                                                                                    filter_zscore=20,
   226                                                                                    groupby_labels=None):
   297                                           
   298         1          136    136.0      0.0      if factor.index.levels[0].tz != prices.index.tz:
   299                                                   raise NonMatchingTimezoneError("The timezone of 'factor' is not the "
   300                                                                                  "same as the timezone of 'prices'. See "
   301                                                                                  "the pandas methods tz_localize and tz_convert.")
   302                                           
   303         1    185870118 185870118.0     70.9      merged_data = compute_forward_returns(prices, periods, filter_zscore)
   304                                           
   305         1        53737  53737.0      0.0      factor = factor.copy()
   306         1          738    738.0      0.0      factor.index = factor.index.rename(['date', 'asset'])
   307         1     55067227 55067227.0     21.0      merged_data['factor'] = factor
   308                                           
   309         1            6      6.0      0.0      if groupby is not None:
   310                                                   if isinstance(groupby, dict):
   311                                                       diff = set(factor.index.get_level_values(
   312                                                           'asset')) - set(groupby.keys())
   313                                                       if len(diff) &gt; 0:
   314                                                           raise KeyError(
   315                                                               "Assets {} not in group mapping".format(
   316                                                                   list(diff)))
   317                                           
   318                                                       ss = pd.Series(groupby)
   319                                                       groupby = pd.Series(index=factor.index,
   320                                                                           data=ss[factor.index.get_level_values(
   321                                                                               'asset')].values)
   322                                           
   323                                                   if groupby_labels is not None:
   324                                                       diff = set(groupby.values) - set(groupby_labels.keys())
   325                                                       if len(diff) &gt; 0:
   326                                                           raise KeyError(
   327                                                               "groups {} not in passed group names".format(
   328                                                                   list(diff)))
   329                                           
   330                                                       sn = pd.Series(groupby_labels)
   331                                                       groupby = pd.Series(index=factor.index,
   332                                                                           data=sn[groupby.values].values)
   333                                           
   334                                                   merged_data['group'] = groupby.astype('category')
   335                                           
   336         1      2583309 2583309.0      1.0      merged_data = merged_data.dropna()
   337                                           
   338         1           11     11.0      0.0      merged_data['factor_quantile'] = quantize_factor(merged_data,
   339         1            3      3.0      0.0                                                       quantiles,
   340         1            2      2.0      0.0                                                       bins,
   341         1     15535693 15535693.0      5.9                                                       by_group)
   342                                           
   343         1      3063046 3063046.0      1.2      merged_data = merged_data.dropna()
   344                                           
   345         1            7      7.0      0.0      return merged_data</pre></div>
    </div><div id="pager-button-area"><a role="button" title="Open the pager in an external window" class="ui-button"><span class="ui-icon ui-icon-extlink"></span></a><a role="button" title="Close the pager" class="ui-button"><span class="ui-icon ui-icon-close"></span></a></div><div class="ui-resizable-handle ui-resizable-n" style="z-index: 90;"></div></body><div></div></html>

**Comment by luca-s** [comment]
I understand your needs but the forward returns depend on the factor data: If you change the factor it might be that your factor universe change too together with the factor values. There is no guarantee that the previous factor universe is the same as the new one. So the API proposed wouldn't be a clean one. 

Also `utils.get_clean_factor_and_forward_returns is` is a simple utility function that you can copy paste it in your NB and modify it to suit your specific needs. I think this would be the easiest way to follow.

However, if you can come up with a clean re-design of `get_clean_factor_and_forward_returns`  that suits your need and it doesn't change the current behaviour we can talk about it.

**Comment by HereticSK** [comment]
Below is the main part of code from `get_clean_factor_and_forward_returns`. If I understand it correctly, it starts with a forward returns dataframe, then it adds the columns of factor, group, and factor_quantile to `merged_data`, one at each step. 

Moreover, the initial `merged_data` is nothing more than the result of `compute_forward_returns(prices, periods, filter_zscore)`, which depends only on `prices`, `periods`, `filter_zscore`, not factor values. 

Simply replacing the line of code `merged_data = compute_forward_returns(prices, periods, filter_zscore)` with something like `merged_data = pre_computed_fwd_return`, everything should be the same.

The main idea should be simple. But I don't know if there is anything more should be considered.
```Python
    merged_data = compute_forward_returns(prices, periods, filter_zscore)

    factor = factor.copy()
    factor.index = factor.index.rename(['date', 'asset'])
    merged_data['factor'] = factor

    merged_data['group'] = groupby.astype('category')

    merged_data = merged_data.dropna()

    merged_data['factor_quantile'] = quantize_factor(merged_data,
                                                     quantiles,
                                                     bins,
                                                     by_group)

    merged_data = merged_data.dropna()

    return merged_data
```

**Comment by luca-s** [comment]
The idea is as what you described. It's so straightforward that it would make sense to you to write your own function that replace get_clean_factor_and_forward_returns and doesn't re-compute the forward returns.

**Comment by luca-s** [comment]
Also `get_clean_factor_and_forward_returns` is not a core part of Alphalens, it's a helper. You can build your own factor_data and call all the tears.* functions without using `get_clean_factor_and_forward_returns`  at all. So it is reasonable to have your own version of `get_clean_factor_and_forward_returns` that suits better your use case

**Comment by HereticSK** [comment]
OK I see . Thanks a lot!

**Comment by luca-s** [comment]
I am closing this now. Feel free to reopen it if required
