### ISSUE TITLE
Log Cumulative Returns does not do log() calculation?

### ISSUE THREAD

**Issue by BlueMatrix007** [quantopian/alphalens#203]
In function plot_cumulative_returns_by_quantile(), the data( cum_ret) used to plot "Cumulative Return by Quantile Figure"  has not been processed by a log fucntion?
![image](https://user-images.githubusercontent.com/15075698/31573916-3ef39628-b0f7-11e7-913e-d099d34d0674.png)

**Comment by luca-s** [comment]
Please see #194
