### ISSUE TITLE
Ann. IR Calculation

### ISSUE THREAD

**Issue by MichaelJMath** [quantopian/alphalens#208]
https://github.com/quantopian/alphalens/blob/738b1a9f538b8cc575c9d431e44890540c52a145/alphalens/plotting.py#L173-L174

Not sure what this calculation is trying to do. I am assuming that IR stands for "Information Ratio". The Information ratio is the ratio of (excess return over a benchmark) / (active risk). According to "The Fundamental Law of Active Management" (FLAM) by Richard Grinold (_Journal of Portfolio Management,_ vol 15, no. 3 1989), the information ratio is a function of the Information Coefficient (IC) and Breadth (N)(breadth being defined as the number of independent forecasts made per year):
![ir](https://user-images.githubusercontent.com/28760724/32199052-5f06782a-bda1-11e7-9a16-f3c0f9a6a2f3.JPG)
Source:  [Extending the Fundamental Law of Investment Management - JP Morgan US Equity Quantitative Research](https://www.jpmorgan.com/cm/BlobServer/Extending_the_Fundamental_Law_of_Investment_Management_.pdf?blobkey=id&blobwhere=1158630145176&blobheader=application%2Fpdf&blobheadername1=Cache-Control&blobheadervalue1=private&blobcol=urldata&blobtable=MungoBlobs)

Using this version of the FLAM, it seems that this piece of code is using the number of trading days as breadth (i.e. the number of independent forecasts in a year), which I think is reasonable, but I'm not understanding why the code divides the IC mean by the IC standard deviation.

I can make a change, but would like some input to make sure I am not missing something.

**Comment by luca-s** [comment]
Funny, if ic_data was the returns that computation would be the Information Ratio (or Sharpe Ratio) assuming the benchmark returns (o risk free returns for SR) being zero.

@twiecki you know anything about that?

**Comment by luca-s** [comment]
Just to add some more information, this is the [relevant commit](https://github.com/quantopian/alphalens/commit/f258f4ff047483531f0468f6022300089853330c)

**Comment by MichaelJMath** [comment]
@twiecki In that case, I'm thinking the calculation to annualize the IC IR/Sharpe ratio may be a bit off. It looks like the code is using the standard formula to annualize a sharpe ratio of excess returns. However, since the information coefficient is independent of the time period calculated it can't be annualized the same way as a return (although the standard deviation in the denominator can be annualized as usual). See my calculations below (which ignore compounding).  T is the number of periods in a year (i.e. T = 252 trading days). 

![sharpe annualization](https://user-images.githubusercontent.com/28760724/32280348-f3392992-bef1-11e7-8b8a-db70a2700516.png)

The yellow box represents the current methodology. I would propose the small change represented by the green box and coded below (which is essentially just moving the parentheses):

`ic_summary_table["Ann. IR"] = ic_data.mean() / (ic_data.std() * np.sqrt(252) )`

Please let me know your thoughts and if I am off base here.

Regarding the name, maybe "Ann. IC IR" or "Ann. IC Sharpe", but I would differ to you and your colleagues on that. Either way, I think it is fine. I think I got confused because of the way it was attempting to annualize the ratio. I thought maybe you were using the IR Ratio proposed in the Fundamental Law of Active Management that I referenced in my earlier comment.

**Comment by luca-s** [comment]
@MichaelJMath your proposed change makes sense to me.

@twiecki what do you think?

**Comment by luca-s** [comment]
@MichaelJMath would you like to submit a PR?
