### ISSUE TITLE
Returns tear sheet: Period wise returns rows incorrectly using total, rather than the mean

### ISSUE THREAD

**Issue by ernestoeperez88** [quantopian/alphalens#211]
I got this inquiry from a Quantopian community member: 

" I think the first two "period wise" rows are not period wise, but total.
... it should be self explanatory. The spread on the one day is the difference of the two rows above, but the other days it is not. That is because they are incorrectly using the total rather than the mean."

He's referring to the following table from the returns tear sheet: 
![screen shot 2017-11-01 at 10 21 28 am](https://user-images.githubusercontent.com/3497470/32280417-36ec0704-bef2-11e7-86aa-daa37bea744a.png)

**Comment by twiecki** [comment]
CC @luca-s

**Comment by luca-s** [comment]
Thank you for reporting this. The same bug was reported in #154 and fixed in #158, but not yet available on Quantopian unfortunately. I am closing this as the bug as been already fixed.
