### ISSUE TITLE
Deprecation warnings for the pandas rolling API

### ISSUE THREAD

**Issue by mmargenot** [quantopian/alphalens#213]
Currently, the plots use `pd.rolling_mean()`, which has been deprecated.

**Comment by mmargenot** [comment]
Wrote up a PR for `rolling_mean` here: https://github.com/quantopian/alphalens/pull/214. I have not done anything for `rolling_apply` yet.

**Comment by mmargenot** [comment]
I'm having a look at `rolling_apply` today.

**Comment by luca-s** [comment]
I think there are no rolling_apply left :) #216
