### ISSUE TITLE
Plots difficult for particular kinds of colorblindness

### ISSUE THREAD

**Issue by mmargenot** [quantopian/alphalens#233]
Namely, the first and last quantiles are G/R, which is a common form of colorblindness.

**Comment by luca-s** [comment]
Has this issue already been handled in pyfolio? If so we could follow the same path.

**Comment by luca-s** [comment]
We should probably define a set of palettes and use them when plotting and we should probably provide a be

**Comment by luca-s** [comment]
Even easier, we could try using `seaborn.set_palette` in [plotting.customize](https://github.com/quantopian/alphalens/blob/master/alphalens/plotting.py#L42) and that should change the default plots palette. Also, there are two plots where we set the palette manually, we should use the default palette in there.

**Comment by mmargenot** [comment]
https://github.com/quantopian/alphalens/pull/245

**Comment by mmargenot** [comment]
https://github.com/quantopian/alphalens/pull/245

**Comment by jameschristopher** [comment]
This issue brings up another interesting aspect (of open source software in general), which is to what extent do we try and make Alphalens accessible to people of various disabilities.

**Comment by mmargenot** [comment]
I think the color of plots is an easy one to deal with. This one came up because I was helping with a workshop and one of the attendees simply could not use Alphalens because of it. 

What would be some other ways to increase accessibility? If there are additional one-line fixes, I think it would only be a good thing to carry them out.
