### ISSUE TITLE
Higher Resolution Timestmaps

### ISSUE THREAD

**Issue by neman018** [quantopian/alphalens#235]
How do I run alphalens if I'm using minute resolution data (instead of daily values like in the examples) and I have factors with second resolution data (and I want to round to the NEXT nearest minute - or whatever my price data resolution is)?

Thanks in advance!

**Comment by luca-s** [comment]
Make sure `prices` contains entries for the timestamps the at which each factor value is computed, those will be the entry prices (buy prices for long positions or sell prices for short positions). The next price after the factor timestamps will be used to compute the 1 period forward returns, the second price after the factor timestamps will be used to compute the 2 period forward returns, and so on.

From utils.get_clean_factor_and_forward_returns:

>  prices : pd.DataFrame
>         A wide form Pandas DataFrame indexed by timestamp with assets
>         in the columns. It is important to pass the
>         correct pricing data in depending on what time of period your
>         signal was generated so to avoid lookahead bias, or
>         delayed calculations. Pricing data must span the factor
>         analysis time period plus an additional buffer window
>         that is greater than the maximum number of expected periods
>         in the forward returns calculations.
>         'Prices' must contain at least an entry for each timestamp/asset
>         combination in 'factor'. This entry must be the asset price
>         at the time the asset factor value is computed and it will be
>         considered the buy price for that asset at that timestamp.
>         'Prices' must also contain entries for timestamps following each
>         timestamp/asset combination in 'factor', as many more timestamps
>         as the maximum value in 'periods'. The asset price after 'period'
>         timestamps will be considered the sell price for that asset when
>         computing 'period' forward returns.

**Comment by luca-s** [comment]
I added an [example NB](https://github.com/quantopian/alphalens/blob/master/alphalens/examples/intraday_factor.ipynb) of an intraday factor.  It doesn't use seconds or minutes resolution but it might help understanding how Alphalens expects the input data to be formatted,
