### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by a-campbell** [quantopian/alphalens#26]
- [x] Verify all arguments and types are correct in docstrings
- [x] README
    - [x] Overview 
    - [x]  link to your code & issue tracker
    - [x] Frequently Asked Questions (FAQ)
    - [x]  How to get support
    - [x] Information for people who want to contribute back
    - [x] Installation instructions
    - [x] explain input data types 
    - [x] Example tear sheet
    - [x] project’s license
    - [x] credits
- [x] Notebook
    - [x] explain calculation of:
       - [x] IC
       - [x] alpha, alpha tstat, beta
       - [x] IR
    - [x] walk through various plots

**Comment by jameschristopher** [comment]
Notebook https://github.com/quantopian/alphalens/pull/51
