### ISSUE TITLE
Clean up backward compat API

### ISSUE THREAD

**Issue by twiecki** [quantopian/alphalens#268]
I think we have kept the backwards compatible API around long enough. can remove in the next release.

**Comment by mmargenot** [comment]
I think we should do this as a secondary release. Put Pyfolio input and other features in a main one and patch out the backwards compatible API in a quick follow-up. Does this make sense? I'd like to still have the backwards-compatible support on Quantopian Research in conjunction with Pyfolio input.

**Comment by luca-s** [comment]
@twiecki and I talked about this today and we had the same thought as you. Let's have the next release first, then we can remove the backwards-compatible support

**Comment by twiecki** [comment]
@luca-s Now that v0.3.0 is out, think we should go ahead on this?

**Comment by luca-s** [comment]
Maybe we should wait and see that new release is running fine on Quantopian? If we needed to create a new release it would be annoying to re-introduce the backwards compatible layer.

**Comment by twiecki** [comment]
Good point.

**Comment by luca-s** [comment]
closed by #286
