### ISSUE TITLE
Travis CI doesn't update the PR status

### ISSUE THREAD

**Issue by luca-s** [quantopian/alphalens#273]
New PR don't have their status updated by Travis CI, even though new Travis CI builds are correctly started and completed. Is it possible that Travis CI needs some rights to access the project?

From https://docs.travis-ci.com/user/github-oauth-scopes/

> On https://travis-ci.org we ask for the following permissions:
> - repo:status: After every build, we update the status of its commit, which is most relevant for testing pull request. This scope gives us the permission to update the commit status as the build starts and finishes.

**Comment by richafrank** [comment]
I'll take a look @luca-s

**Comment by luca-s** [comment]
It seems you fixed that, all is back to normal now.

**Comment by richafrank** [comment]
Yep - Travis's access to the quantopian org had been removed. Should be granted again.
