### ISSUE TITLE
Conda installation instructions not included in the README

### ISSUE THREAD

**Issue by TimShawver** [quantopian/alphalens#278]
Looks like alphalens is available on conda-forge now.  Should we add installation instructions to the README in this repo, so conda users know that we have them covered?

**Comment by luca-s** [comment]
This sounds like a good idea. @TimShawver Would you like to update the README on a new pull request?

**Comment by TimShawver** [comment]
Sure: https://github.com/quantopian/alphalens/pull/280

**Comment by luca-s** [comment]
thank you!
