### ISSUE TITLE
Example notebooks use deprecated yahoo API

### ISSUE THREAD

**Issue by TimShawver** [quantopian/alphalens#279]
I get the following error when attempting to pull data from yahoo via pandas datareader:

![screen shot 2018-02-21 at 10 55 34 pm](https://user-images.githubusercontent.com/5055866/36519653-b8b8e5ac-175a-11e8-996a-b6fe80e564b7.png)

Looks like I have the same problem in the qgrid demo notebook.

**Comment by luca-s** [comment]
Thank you for reporting the issue @TimShawver. Yahoo data has been giving problems for quite some time. I recently fixed the example NBs (after release v0.2.1) and now they are  broken again. I won't chase Yahoo anymore, not until their API stabilize. Maybe it's time to build examples on other data source. Would you like to provide a PR?

**Comment by TimShawver** [comment]
Yea sounds like we'll need to use another data source.  I won't have time to work on this unfortunately, just wanted to make sure you were aware of the issue.  Last time I checked the Yahoo API was working at least intermittently, so it was news to me that it had stopped working entirely.

**Comment by luca-s** [comment]
Indeed I wasn't aware of the new API breakage, thanks for reporting this.

**Comment by luca-s** [comment]
Closed by #285
