### ISSUE TITLE
Add option for "zero aware" quantiles/bins

### ISSUE THREAD

**Issue by luca-s** [quantopian/alphalens#281]
Sometimes a user might want to analyze a factor where positive and negative values are treated separately. Since the amount of positive values might be different than the negative ones (the factor is biased) the `quantiles` option wouldn't do a good job in separating positive from negative values. Currently the only way to separate positive from negative values is to use the `bins` option, providing custom bin ranges. Is this enough or do we want to improve it?

**Comment by twiecki** [comment]
I think an option to use the quantile method separately for positive and negative values would be a useful feature.

**Comment by luca-s** [comment]
Do you have a suggestion for option name and description? :)

**Comment by twiecki** [comment]
`split_pos_neg`?

**Comment by twiecki** [comment]
`Compute quantile boundaries separately for positive and negative signal values. This is useful if your signal is centered and zero is the separation between long and short signals, respectively."

**Comment by twiecki** [comment]
@luca-s Did you plan to add that in?

**Comment by luca-s** [comment]
I am not planning on working on this soon. The change is trivial but there are API change and unit testing updates involved, which takes time. Anybody who feels like working on this is welcome.

**Comment by eigenfoo** [comment]
Hi! I can take this over. Perhaps `by_sign` would be a better name? It looks like we already have a `by_group` parameter, which has a similar functionality: compute quantile buckets separately for each group. We'd like to compute quantile buckets separately for positive/negative values, so it seems logical to have a similar name.

@twiecki thoughts?

**Comment by twiecki** [comment]
hmm, I like the idea just not sure that logic becomes apparent to users. `zero_aware` feels a bit more intuitive to me. Thoughts @luca-s?

**Comment by luca-s** [comment]
`zero_aware` seems good to me too

**Comment by luca-s** [comment]
Closed by #306
