### ISSUE TITLE
Release on PyPi

### ISSUE THREAD

**Issue by a-campbell** [quantopian/alphalens#29]

**Comment by jameschristopher** [comment]
Did we ever do this?

**Comment by twiecki** [comment]
I don't think so, should definitely do a 0.1 release.

**Comment by jameschristopher** [comment]
Yeah just thinking about that now we've got some more community PRs when would be a good time. Also we have in the read me that you can pip install, I'm actually surprised no one has written up an issue for that yet.

**Comment by ehebert** [comment]
:+1: on uploading to PyPI. (Noticed lack of PyPI release when GitHub servers were down today.)

**Comment by twiecki** [comment]
It's on pypi now.
