### ISSUE TITLE
Support for other types of regressions other than Spearman?

### ISSUE THREAD

**Issue by chunky123** [quantopian/alphalens#290]
I think although spearman is a great way to measure correlation, it might be convenient to allow the user to specify alternative methods (maybe by allowing some lambda input?). Pointing it out here to see if anyone else feels the same.

**Comment by luca-s** [comment]
I have never had the need for another type of correlation but I would be curious to know if there is a specific scenario where this might be useful, that is where another type of correlation would do a better job.

**Comment by luca-s** [comment]
I am closing this for lack of use cases. Feel free to reopen the issue if required
