### ISSUE TITLE
create_factor_tear_sheet function not available on tears.py?

### ISSUE THREAD

**Issue by Konsang** [quantopian/alphalens#308]
I am trying to create a factor tear sheet but an error throws up every time. I checked tears.py and couldn't find create_factor_tear_sheet. Has this function been renamed or is there any other alternative to create a factor based tear sheet with two quantiles?

**Comment by luca-s** [comment]
The API changed some time ago.

OLD API
```
alphalens.tears.create_factor_tear_sheet(alphas['my_factor'], pricing)  
```

NEW API
```
factor_data = alphalens.utils.get_clean_factor_and_forward_returns(alphas['my_factor'], pricing)  
alphalens.tears.create_full_tear_sheet(factor_data)  
```

Have a look at the [examples](https://github.com/quantopian/alphalens/tree/master/alphalens/examples), they are up to date and very useful.

**Comment by Konsang** [comment]
Thank you for your prompt response.
