### ISSUE TITLE
Biased Mean Quantile Returns for Non-Equal Bins

### ISSUE THREAD

**Issue by MichaelJMath** [quantopian/alphalens#309]
I was doing a study today, and I came across a potential issue with the `performance.mean_return_by_quantile` logic in the returns tear sheet. I guess it is not so much an issue with the logic of that function, but more so how it is used in building the tear sheet. I think this would only be an issue if a user created bins or quantiles with a non-uniform number of observations in each bin over time. In other words, the amount of stocks in each bin changes over time.

If the number of stocks in a bin is correlated with market direction, this could bias the mean return calculation. For instance, if a factor quantile tends to have a lot of stocks when the market is going up, it will receive a higher weight on those up-days and will thus bias the mean return upwards for that factor quantiles. 

[Here is an example I created.](https://docs.google.com/spreadsheets/d/1vVncTm_TKilb8bYjz5A2BdZ5pkacef-JgJrMApdEzig/edit?usp=sharingl) Note how it affects the mean return of the spread of going long the best quantile and short the worst quantile.

I believe the `mean_return_by_quantile` function already has the ability to group by date, so therefore, you could calculate the mean return for each quantile and date first, and then take the mean by quantile. 

Am I thinking about this right?

**Comment by luca-s** [comment]
Good, point. I totally agree with you. To tell the truth I thought Alphalens was already working accordingly with the solution you are proposing, but unfortunately it is not. 

> I believe the mean_return_by_quantile function already has the ability to group by date, so therefore, you could calculate the mean return for each quantile and date first, and then take the mean by quantile.

I agree and I would do that inside `mean_return_by_quantile`. Currently the function compute the mean returns by date only if `by_date` option is true. We should do that all the time instead and finally take the mean by quantile averaging the daily mean returns only if `by_date` is false.

Do you agree?

**Comment by MichaelJMath** [comment]
I would think that would be the way to go unless there are somehow other use cases where you would actually want the current functionality. However, I can't really think of any cases where that would be the case off the top of my head. So yah, I agree with you.

**Comment by luca-s** [comment]
@MichaelJMath would you like to submit a PR? I tried working on this but I am busy on something else at the moment.

**Comment by MichaelJMath** [comment]
Sure, I'll try to get to it this weekend.
