### ISSUE TITLE
question about create factors

### ISSUE THREAD

**Issue by fzhcary** [quantopian/alphalens#310]
how do I use the last N days of closing prices to create factors? for example, using RSI to create factors that can be used in alphalens? I am talking about calculation not using quantopian's pipeline.

**Comment by luca-s** [comment]
Please have a look at the [examples](https://github.com/quantopian/alphalens/tree/master/alphalens/examples), they don't use Quantopian's Pipeline.  Once you have the price data you can make use of Pandas' functionalities to compute what you need. Also make sure to read the documentation of ```alphalens.utils.get_clean_factor_and_forward_return``` to understand how to properly format the factor data.

**Comment by fzhcary** [comment]
Thanks a lot for your quick response! It seems that The examples create
factors by simulated data. How do I create factors based on prices series
for example RSI?
Thanks much!

**Comment by luca-s** [comment]
I believe you haven't looked at all the examples. Some of them fetch data from yahoo or google but I believe their services haven't been reliable recently but I haven't tried them for quite some time. 
Also please keep this and future issues focused on Alphalens specific questions.  Questions on how to query marked data or how to use python to compute RSI are out of topic. Thanks.

**Comment by luca-s** [comment]
@fzhcary It seems that your index is using dates in descending order. Try inverting the order.
