### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by fzhcary** [quantopian/alphalens#311]
ValueErrorTraceback (most recent call last)
<ipython-input-35-2612462f1a20> in <module>()
----> 1 alphalens.tears.create_summary_tear_sheet(factor_data)

/home/frank/Envs/alphalens/local/lib/python2.7/site-packages/alphalens/plotting.pyc in call_w_context(*args, **kwargs)
     43             with plotting_context(), axes_style(), color_palette:
     44                 sns.despine(left=True)
---> 45                 return func(*args, **kwargs)
     46         else:
     47             return func(*args, **kwargs)

/home/frank/Envs/alphalens/local/lib/python2.7/site-packages/alphalens/tears.pyc in create_summary_tear_sheet(factor_data, long_short, group_neutral)
    209                                      by_group=False,
    210                                      demeaned=long_short,
--> 211                                      group_adjust=group_neutral)
    212 
    213     mean_quant_rateret = \

/home/frank/Envs/alphalens/local/lib/python2.7/site-packages/alphalens/performance.pyc in mean_return_by_quantile(factor_data, by_date, by_group, demeaned, group_adjust)
    648     group_stats = factor_data.groupby(grouper)[
    649         utils.get_forward_returns_columns(factor_data.columns)] \
--> 650         .agg(['mean', 'std', 'count'])
    651 
    652     mean_ret = group_stats.T.xs('mean', level=1).T

/home/frank/Envs/alphalens/local/lib/python2.7/site-packages/pandas/core/groupby.pyc in aggregate(self, arg, *args, **kwargs)
   4289         versionadded=''))
   4290     def aggregate(self, arg, *args, **kwargs):
-> 4291         return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)
   4292 
   4293     agg = aggregate

/home/frank/Envs/alphalens/local/lib/python2.7/site-packages/pandas/core/groupby.pyc in aggregate(self, arg, *args, **kwargs)
   3722 
   3723         _level = kwargs.pop('_level', None)
-> 3724         result, how = self._aggregate(arg, _level=_level, *args, **kwargs)
   3725         if how is None:
   3726             return result

/home/frank/Envs/alphalens/local/lib/python2.7/site-packages/pandas/core/base.pyc in _aggregate(self, arg, *args, **kwargs)
    537             return self._aggregate_multiple_funcs(arg,
    538                                                   _level=_level,
--> 539                                                   _axis=_axis), None
    540         else:
    541             result = None

/home/frank/Envs/alphalens/local/lib/python2.7/site-packages/pandas/core/base.pyc in _aggregate_multiple_funcs(self, arg, _level, _axis)
    594         # if we are empty
    595         if not len(results):
--> 596             raise ValueError("no results")
    597 
    598         try:

ValueError: no results

<Figure size 432x288 with 0 Axes>

factor_data.head()
-1D	-5D	-10D	factor	factor_quantile
date	asset					
2015-05-21 00:00:00+00:00	AAPL	-0.010123	-0.018571	-0.046655	1.028533	4
C	0.000912	-0.004376	-0.027899	0.970992	1
INTC	-0.005365	-0.017288	-0.038897	1.080880	5
JPM	-0.002551	-0.009002	-0.032258	0.976010	2
2015-05-20 00:00:00+00:00	AAPL	0.000077	-0.031139	-0.038828	1.027667	4

alphalens version: 0.3.2

**Comment by luca-s** [comment]
answered in #310
