### ISSUE TITLE
factor_rank_autocorrelation infers turnover period in calendar space while periods could have different time space

### ISSUE THREAD

**Issue by twiecki** [quantopian/alphalens#323]
https://github.com/quantopian/alphalens/blob/master/alphalens/performance.py#L796 infers the factor frequency by finding the space between factors. It uses pandas and thus returns a time-difference in calendar space. However, `period='10D'` most likely refers to 10 trading days (14 days) if factors and prices are only present for trading days. This then causes a problem in the next line https://github.com/quantopian/alphalens/blob/master/alphalens/performance.py#L797 where `shift=0` and autocorrelation is shown as 1 constantly.

**Comment by luca-s** [comment]
Closed by #324
