### ISSUE TITLE
bug? in utils.py

### ISSUE THREAD

**Issue by woshihaofeng** [quantopian/alphalens#331]
in utils.py , function: compute_forward_returns() 
 entries_to_test = min(
            30,
            len(forward_returns.index) - period,  
            #when len(prices.index) = 50 ,len(forward_returns.index)=30, and have the same last date. period=1, end = prices.index[p_idx + period] index will out of bounds, 
            #len(forward_returns.index), 
            len(prices.index) - period
)

**Comment by luca-s** [comment]
I guess you  are right, thanks for reporting this.

**Comment by luca-s** [comment]
@woshihaofeng  Would you like to submit a PR?

**Comment by woshihaofeng** [comment]
just get it when testing example "event_study_synthetic_data.ipynb"

**Comment by luca-s** [comment]
@woshihaofeng could you tell me what Alphalens, pandas and numpy versions are you using?

**Comment by woshihaofeng** [comment]
sure. Alphalens is 0.3.6, pandas is 0.23.4, numpy is 1.15.4

**Comment by luca-s** [comment]
I am not getting any error when running "event_study_synthetic_data.ipynb". Did you modify the input data in the example?If so, could you tell me how to reproduce the error you are seeing?
