### ISSUE TITLE
function of utils.infer_trading_calendar

### ISSUE THREAD

**Issue by wuyunhua** [quantopian/alphalens#333]
## Problem Description
In utils.infer_trading_calendar function, the variable days_of_the_week seems incorrect?
days_of_the_week = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
if 'Sat' and 'Sun' are included, then the weekend will be list  in the trade days。

**Please provide a minimal, self-contained, and reproducible example:**
```python
index_1 = pd.date_range('2019-01-01',periods=15)
index_2 = pd.date_range('2019-01-01', periods=30)
custom_bus_day = infer_trading_calendar(index_1, index_2)
custom_bus_day.calendar.weekmask # array([ True,  True,  True,  True,  True,  True,  True])
custom_bus_day.calendar.holidays # array([], dtype='datetime64[D]')

```

## Versions

* Alphalens version: 0.3.6
* Python version: 3.6.8

**Comment by luca-s** [comment]
Thanks for reporting this @wuyunhua but the function is working as expected: it infers the calendars based on the dates you passed. Since the dates contain the weekends, then the inferred calendar has weekends too
