### ISSUE TITLE
the Tear Sheet is not showing good.

### ISSUE THREAD

**Issue by gnyuan** [quantopian/alphalens#366]
## Problem Description

I'm runinng on Windows 10, and it outputs a mess up figure. 

![1111](https://user-images.githubusercontent.com/6140657/78106125-582a4a80-7425-11ea-9676-98b81c572b8a.png)
 
```python
# I look into codes in tears.py, everything looks good. 
# maybe this is the place where to set height of subplots. 
self.fig = plt.figure(figsize=(14, rows * 7))
self.gs = gridspec.GridSpec(rows, cols, wspace=0.4, hspace=0.3)
```

## Versions

* Alphalens version: 0.3.6
* Python version: 3.6.5
* Pandas version: 0.23.0
* Matplotlib version: 2.2.3

**Comment by twiecki** [comment]
What happens if you call `plt.tight_layout()`?

**Comment by gnyuan** [comment]
> What happens if you call `plt.tight_layout()`?

No, I just copy two lines according to the document.
Maybe there is something to do with OS env?

```Python
# factors_df and prices_df are dataframe which formatted.
factor_data = alphalens.utils.get_clean_factor_and_forward_returns(factors_df['turnover_rate'],prices_df)
alphalens.tears.create_returns_tear_sheet(factor_data)
```

**Comment by gnyuan** [comment]
I have figured out what happen. I'm running on PyCharm. In PyCharm Python is in *interactive mode*, and the maximum figsize of a matplotlib figure is limited.
We should first add two lines in the beginning, which makes matplotlib using Agg backen to draw figures and it will break the limit of figsize.
```python
import matplotlib
matplotlib.use('Agg')
```

then in `close` method of tears.py, save figure as a png file.
```python
    def close(self):
        plt.savefig('output.png')
        plt.close(self.fig)
        self.fig = None
        self.gs = None
```

Thanks to these two links.
[https://stackoverflow.com/questions/50257509/is-there-maximum-figsize-in-matplotlib](url)
[https://stackoverflow.com/questions/49284893/matplotlib-while-debugging-in-pycharm-how-to-turn-off-interactive-mode](url)

**Comment by twiecki** [comment]
Thanks for posting the solution!
