### ISSUE TITLE
Anyone can explain how the factors are bined?

### ISSUE THREAD

**Issue by luisvelo** [quantopian/alphalens#391]
## Problem Description
I'm working through some examples that come from the book from Stefan Jansen. I want to understand how the factors are attributed to bins and what's the meaning of zero_aware.

quantize_factor is the function that makes the attribution
code from quantile_calc inside quantize_factor
            if _quantiles is not None and _bins is None and not _zero_aware:
                return pd.qcut(x, _quantiles, labels=False) + 1

    factor_quantile = factor_data.groupby(grouper)['factor'] \
        .apply(quantile_calc, quantiles, bins, zero_aware, no_raise)

called with the below code (call it "normal call")
lr_factor_data = get_clean_factor_and_forward_returns(factor=lr_factor,
                                                      prices=trade_prices,
                                                      quantiles=5,
                                                      periods=(1, 5, 10, 21))

I was expecting that the assignment should be "direct". But is not. Below code
pd.qcut(lr_factor_data['factor'], q=5, labels=False)

Does not attribute the same quintiles that "normal call" attributes.

Also, I do not understand what "zero aware" is doing. It puts on the same quintile positive and negative factor values, I do not grasp well what's the intention.

## Versions

* Alphalens version: 0.36
* Python version: 3.8
* Pandas version: 1.1.3

**Comment by luca-s** [comment]
You can control the binning function with the `quantiles` and `bins` arguments. When `quantiles` is used the factors bins are built using the notion of [quantile](https://en.wikipedia.org/wiki/Quantile): so the factor values distribution will be split in equally sized  quantiles, each split of this distribution is a quantile. When  `bins` is used, then the factor values distribution will be split in equal value ranges. In this case you might have different number of entries per bin.

You might want to have a look here for more information: https://github.com/quantopian/alphalens/blob/master/alphalens/examples/alphalens_tutorial_on_quantopian.ipynb

**Comment by luisvelo** [comment]
found the answer in the end, binning is done by date and then on factor:

Since financial market data are extremely noisy, it would be very hard to find a correlation between a specific factor value and future returns. For this reason Alphalens computes the statistics on factor quantiles instead on the factor values themselves. Quantiles are created taking the daily factor values distribution and split it into equal-sized buckets based on their values. This operation is done on a daily basis. The idea behind quantiles is that grouping stocks helps to increase the signal-to-noise ratio.

https://github.com/quantopian/alphalens/blob/master/alphalens/examples/alphalens_tutorial_on_quantopian.ipynb
