### ISSUE TITLE
WIP AlphaLens Review Notes

### ISSUE THREAD

**Issue by ssanderson** [quantopian/alphalens#56]
## General Notes:
- What is AlphaLens' convention for symbol identifiers going to be?  I continue
  to be of the opinion that using ticker symbols is broken by design in our
  domain.  If we just want to use arbitrary, guaranteed-unique identifiers, I
  think that's fine, but if we do that we need to be careful to not use
  string-specific methods when working with asset indices.
- What is AlphaLens' convention for price adjustments going to be?  All the
  algorithms, as far as I can tell, are assuming prices that are adjusted
  relative to the end date of the alpha period.  Many users won't have an easy
  way to get data in that format (it's currently quite difficult to get such
  data on quantopian for example.)  I'd expect, moreover, that it's often
  easier for users to provide adjusted forward returns than it is for them to
  provide the adjusted prices that yield those returns, but there's no way for
  me to run a tearsheet using my own forward returns.  A fix for this would be
  to make `create_factor_tear_sheet` accept the same data format as all the
  plotting functions, and require that the user call `format_input_data` (see
  notes below for thoughts on that function's name) if they want to convert
  wide-form data into narrow-form data.
- There are a bunch of notes scattered across various functions on the
  importance of correctly aligning your pricing data with your factor
  calculations, but nowhere that I can find is it clearly specified what the
  expectations are for how factor and pricing data should be represented.
- There's at least one place where we're including vendor-specific data in
  Alphalens.  Both for licensing reasons, and in the interest of ensuring
  generality to all users, I think we probably should avoid providing
  vendor-specific data.
- There don't seem to be any tests for the top-level plotting functions that
  actually invoke the calculation functions.  It would be nice if we had
  coverage of the functions we actually expect users invoke.  This isn't an API
  issue, but it makes me nervous about the reliability and correctness of the
  plotting functions as we make changes.
- There are a bunch of computation functions
  (e.g. `compute_mean_returns_spread` and `mean_return_by_quantile`) that
  conditionally return different numbers of values based on boolean parameters.
  Almost all the call-sites for these are broken because they're
  unconditionally unpacking the result into a fixed number of values.
  Generally speaking, I'd recommend against functions that return different
  numbers of values, precisely because they make call sites much more
  complex. In most of these cases, we only ever test in the mode that computes
  the maximum number of values, so I'd recommend just making that always the
  behavior instead of having buggy optional behavior.
- We have a few parameter names that refer to values of different types in different functions (e.g. `std_err`, which is sometimes a bool and sometimes a series.)
- We're missing test coverage for several important, complex functions:
  - There's no test coverage whatsoever for `tears.py`, despite the fact that
    we do a substantial amount of meaningful, tricky computation there.
  - `mean_information_coefficient` is uncovered when `len(grouper) == 0`.
  - `factor_returns` is uncovered when `long_short` is False.
  - `factor_alpha_beta` is uncovered when `factor_daily_returns` is None. (Do
    we need that case at all?).
  - `compute_forward_returns` is uncovered when `filter_zscore` isn't passed
    (do we need that case? All the docstrings warn about it being unsafe, but
    it's the only thing we ever use apparently?).
  - There's no coverage at all for `mean_return_by_quantile`, or
    `compute_mean_returns_spread`, or `format_input_data`.  (And there are
    currently bugs in the only call-sites of `compute_mean_returns_spread` and
    `mean_return_by_quantile`: See Below).
- Most of the docstrings have typos of varying degrees of severity.
### `tears.py`
- `from plotting import *`: Please don't do this.  It immediately breaks any
  intelligent editor's ability to tell you where names come from, and it
  prevents any linting tool from telling you about serious errors like
  undefined variable names.
#### `create_factor_tear_sheet`

Most of the comments here apply to the parameters with the same names elsewhere:
- The docstring descriptions here could be clearer about what the content of
  the expected data is.  Should factor/prices/sectors be floats? Strings?
  Ints?  This comment applies to most of the other API functions.
- `sector_plots`: I would probably call this `show_sector_plots` to be clearer
  that this toggles whether or not to show them (as opposed to, say,
  controlling the number of sector plots).
- Why can `filter_zscore` only be an `int`?  It seems like this would be
  perfectly fine as a float.  This is also noted as incorporating lookahead
  bias.  When is it safe for a user to supply this parameter?  If it's not
  safe, why does it exist?  Also, filtering away outliers after computing
  zscore still has the effect of compressing the z-scores of all our other data
  observations.  Are we okay with that distortion?
- pedantic comment: `days` is annotated as list, but the default is a tuple
  (the tuple default is reasonable).  The correct annotation is probably
  something like `sequence[int]`.  More seriously, if I pass in my own list,
  this function **mutates that list in place**!  We should make a copy if we
  need to change input data in place.
### `performance.py`

Several functions in this file accept an argument named `std_err`. Sometimes
it's a bool indicating whether an optional value should be computed.  Other
times, it's a Series of computed values.  Most of the boolean invocations are
subtly broken at their only call-sites, so I'd argue we should just remove
them.  If we decide they're really important, I'd rename the bools to something
like `compute_std_err`, to be clearer that it's a toggle and not the computed
values themselves.
#### `factor_alpha_beta`
- I'm a little surprised this doesn't have a per-sector mode.  Is sector
  exposure of factors not something we're generally interested in
  plotting/knowing?  Is that already covered somewhere else?
#### `quantize_factor`
- This currently returns floats.  It should return ints or categoricals.
- "A list of equities and their factor values indexed by date.": `list` means a
  specific datastructure in Python.  Especially in documentation of a parameter
  to a function, you don't want to say `list` when it's not what you actually
  mean.  This appears in a bunch of places:
        `
        alphalens/performance.py:144: A list of equities and their factor values indexed by date.
        alphalens/performance.py:182: A list of equities and their factor values indexed by date.
        alphalens/performance.py:230: A list of equities and their factor values indexed by date.
        alphalens/performance.py:266: A list of equities and their N day forward returns where each column contains the N day forward returns.
        alphalens/utils.py:154: A list of equities and their factor values indexed by date.
        alphalens/utils.py:163: A list of equities and their sectors.
        alphalens/utils.py:178: A list of equities and their factor values indexed by date,
        docs/source/conf.py:99: # A list of ignored prefixes for module index sorting.
  `
#### `factor_rank_autocorrelation`
- This is parameterized on a time rule, but the docstring explicitly talks
  about weeks.
### `compute_mean_returns_spread`
- This sometimes returns a single Series and sometimes a pair of Series', but
  the only call site is in `tears.py`, where we do:
  `
  mean_ret_spread_quant, std_spread_quant = perf.compute_mean_returns_spread(
      mean_ret_quant_daily, quantiles, 1, std_err=std_quant_daily)
  `
  This will crash if we ever don't pass `std_err`.
### `mean_return_by_quantile`
- This has the same bug as `compute_mean_returns_spread`: we're always
  unpacking at call-sites, but this conditionally returns a tuple.
#### `format_input_data`
- The name here is pretty generic.  Is there a clearer description of what this
  does?
## Example Notebook Line Notes:
- typo: "insturments"
- typo: "is not nessisarily important"
- run-on sentence: "Trading algorithms cover execution and risk constraints,
  the business of turning predictions into profits." (I'd change the comma to a
  colon.)
- reference to qfactor: "qfactor does not contain analyses of things like..."
- `ticker_sector = {...}`: it'd be nice if there was some context/explanation
  for what this giant dict is (e.g. "This is an example of a constant sector
  mapping ...").
- `from pandas.io.data import DataReader`: pandas.io.data is deprecated.  We
  should use pandas_datareader.
- `for ticker in ticker_sector.keys()`: we don't need `.keys()` here.
- "The pricing data passed to alphalens should reflect the next available price
  after a factor value was observed at a given timestamp."  What does it mean
  for "a factor value to be observed at a given timestamp"?  This seems both
  important and tricky.  We should try to be very clear, both in our
  documentation and in our internal usage, exactly what it means to label an
  observation with a given day.  This will also get **much** harder if we ever
  start caring about non-NYSE calendars, or if we want to be able to ingest and
  analyze non-daily data: are either of those things in the near-term roadmap?
- typo: "how our factor looks accross"
- reference to qfactor: "you'll need to pass qfactor a sector mapping"
- wording: "This mapping can come in the form of a MultiIndex Series" should be
  "MultiIndexed"
- reference to qfactor: " you may also pass qfactor a dict of sector names"
- wording: "Returns analysis gives us a very raw and real description of a
  factor's value."  I'm not sure what this means.
- typo: "we can get an idea about the consitency ..."
- wording: "Turnover Analysis gives us an idea about the dynamic nature of a
  factor's make up." This also feels too vague to be useful.  Is there
  something more precise we can say here?
- wording (nitpick): "Factor turnover is super important ..." 'super' is
  suddenly very informal relative to the tone of the rest of the tutorial.

**Comment by a-campbell** [comment]
changed `from plotting import *` in `create_full_tear_sheet` https://github.com/quantopian/alphalens/commit/e8e3d7bd5d4a0b64235a19fbe9b919a08687c634

**Comment by jameschristopher** [comment]
Below fixed in https://github.com/quantopian/alphalens/pull/57

- [ ] remove vendor specific data
- [ ] removed conditional return values
- [ ] fixed `std_err` confusing types
- [ ] represented form of data
- [ ] changed `plotting import *`
- [ ] docstring changes/typos
- [ ] renamed to `show_sector_plots`
- [ ] fixed `days` mutate in place 
- [ ] `quantize_factor` now returns ints
- [ ] changed name of `format_input_data`
- [ ] fixed all example notebook issues
- [ ] removed all references to qfactor

**Comment by luca-s** [comment]
I believe the majority of the issues reported here are fixed and at this point it would be worth create a separate issue for each of still open ones. At least they would have a chance to be considered.

The issues that I can see are relevant are:
- test coverage for the plotting functions is still missing but it is covered in details here #218
- the `filter_zscore` parameter is still there in its glory but it hasn't an issue associated
