### ISSUE TITLE
days default parameter `1` persists even if new iterable is passed

### ISSUE THREAD

**Issue by jameschristopher** [quantopian/alphalens#64]
so this is intentional so that their is alway some period to calculate on. Not sure if this is the right behavior, it's kind of annoying as a user. 1 is explicitly passed in one function referenced [here](https://github.com/quantopian/alphalens/issues/66). This issue could probably be resolved in the fix for https://github.com/quantopian/alphalens/issues/66 (same as above).

**Comment by luca-s** [comment]
Unfortunately the [Average Cumulative Returns by Quantile plot](https://github.com/quantopian/alphalens/commit/b5c80f2d0f1ada94abdc81ef0ab4cde639af2cfc) relies on daily returns. A workaround would be to avoid the plot if period of 1 is not present but then it would be a little weird from user point of view

**Comment by twiecki** [comment]
@luca-s Couldn't just the avg cumulative returns plot add the 1-day returns but not require it at the level of the tear sheet?

**Comment by luca-s** [comment]
Sure, I can do that. Also, top+bottom quantile turnover and factor rank autocorrelation plots need a little fix in case 1-day period is not present and turnover_for_all_periods is False

**Comment by twiecki** [comment]
@luca-s thanks.
