### ISSUE TITLE
Top and Bottom Quantile Daily Turnover for each day/period

### ISSUE THREAD

**Issue by luca-s** [quantopian/alphalens#68]
Top and Bottom Quantile Daily Turnover plot

The plot shows only the daily turnover, but It would be more interesting to plot the turnover after X days, for each X in 'days' (the create_factor_tear_sheet's argument). This suggested behaviour is a superset of the current one because a user can add '1' to 'days' argument to get the current behaviour.

**Comment by jameschristopher** [comment]
I think this is also a good idea for the same reasoning we talked about in https://github.com/quantopian/alphalens/issues/69
