### ISSUE TITLE
Factor Rank Autocorrelation for each day/period

### ISSUE THREAD

**Issue by luca-s** [quantopian/alphalens#69]
Factor Rank Autocorrelation plot

The plot shows only the daily autocorrelation, but It would be more interesting to plot the autocorrelation after X days, for each X in 'days' (the create_factor_tear_sheet's argument). This suggested behaviour is a superset of the current one because a user can add '1' to 'days' argument to get the current behaviour.

**Comment by jameschristopher** [comment]
This idea makes complete sense to me. The way we are currently doing it is with a pandas timerule, I'm kind of debating whether we want to eschew pandas timerules all together in the package, and just focus on a number of periods analysis. Right now there is kind of a mix, not sure how i feel about that

**Comment by luca-s** [comment]
The current rule used by the tear sheet is time_rule='D'. That means it works fine If we pass daily factors/data to the tear sheet (because it won't do any resampling at all) but it will result in surprisingly graph if we pass minutely/weekly (anything that is not daily) data.

It seems to me it would make sense to make the resampling an option (used only by aware users) and let the code that follows the resampling decides the autocorrelation period:

In factor_rank_autocorrelation function:

`autocorr = asset_factor_rank.corrwith(asset_factor_rank.shift(1), axis=1)`

shift(1) should be changed with shift(period).

**Comment by jameschristopher** [comment]
That sounds good I'd go ahead and submit a PR.
