### ISSUE TITLE
Making forward returns "demeaning" optional

### ISSUE THREAD

**Issue by luca-s** [quantopian/alphalens#72]
The forward returns used for plotting are converted to returns relative to mean. While this is a very clever choice (the code is a constant surprise of many smart ideas, well done!) it implies a long short portfolio and that is not always the case. One might be interested to see if their signal can be profitable in a long (or short) only portfolio over a particular time period. So, why not making the demeaning optional?

Alphalens is shuch a great swiss knife, so why using the blade only? :D

Many thanks!

**Comment by jameschristopher** [comment]
Is there a specific function you have in mind?

**Comment by luca-s** [comment]
Inside create_factor_tear_sheet the following functions plotting.plot_quantile_returns_bar, plotting.plot_quantile_returns_violin and plotting.plot_cumulative_returns_by_quantile are called with returns calculated via perf.mean_return_by_quantile.

perf.mean_return_by_quantile calls utils.demean_forward_returns (the function that actually performs the "demean") and there is no way for the user to avoid that behaviour. So they end up looking at biased returns if they intend to run a long only portfolio.

Also, the function plotting.plot_cumulative_returns is called with returns calculated via perf.factor_returns. The latter function has a concept of long/short or long only portfolio (long_short argument), but there is no option for the user that simply calls create_factor_tear_sheet to switch that option.

**Comment by luca-s** [comment]
PR #77

**Comment by twiecki** [comment]
Closed by #77.
