### ISSUE TITLE
Add pandas and numpy versions to Travis builds

### ISSUE THREAD

**Issue by jameschristopher** [quantopian/alphalens#84]

**Comment by georgh0021** [comment]
Not sure what this means... both [the setup file](https://github.com/quantopian/alphalens/blob/master/setup.py#L13) and [the travis yaml](https://github.com/quantopian/alphalens/blob/master/.travis.yml#L27) shows that `pandas` and `numpy` are already installation requirements, and that Travis sets up a `virtualenv` with the required versions when running builds.

@luca-s maybe you have some context on this issue?

**Comment by luca-s** [comment]
No really, I never really looked at this issue actually

**Comment by georgh0021** [comment]
Alright then, closing this issue now.

**Comment by jameschristopher** [comment]
Id like to do something like this at some point. https://github.com/quantopian/empyrical/blob/master/.travis.yml

**Comment by georgh0021** [comment]
Ah, I see! Thanks for clarifying, @jameschristopher!

Reopening so we can deal put this on our queue.

**Comment by mmargenot** [comment]
Now is probably a good time to revisit this, since we have changed the `pandas` requirement. I'm modifying the `.travis.yml` to be more similar to `zipline` and `empyrical`.

**Comment by jameschristopher** [comment]
Max I can mess around with this if you don't have a WIP

**Comment by twiecki** [comment]
@jameschristopher It should be pretty straight-forward to copy the pattern from pyfolio: https://github.com/quantopian/pyfolio/blob/master/.travis.yml

**Comment by mmargenot** [comment]
That would be great, @jameschristopher

**Comment by luca-s** [comment]
With PR #244 alphalens now testes multiple pandas versions as as pyfolio does. Do we need to test multple numpy versions too? Or can we close this issue?

**Comment by luca-s** [comment]
Pyfolio doesn't test multiple numpy versions while Empyrical does it. At the moment I don't see the necessity to test multiple numpy versions in Alphalens but please let me know your experience on numpy api breakage.

**Comment by luca-s** [comment]
Just to be clearer, my thought is that Alphalens relies on Pandas so it has to test its compatibility with multiple Pandas versions (and it does), in turn  Pandas tests its compatibility with multiple numpy versions, so it shouldn't be necessary for Alphalens to test that too. But this thought might be naive so if  someone has already experienced bugs due to changes in numpy version please let us know, otherwise we could close this issue.

**Comment by richafrank** [comment]
We have empyrical's tests running on different versions of numpy, but I think that might just be because it's easier to `conda install` older pandas with older numpy and newer pandas with newer numpy. 

I agree with your assessment @luca-s : Unless there are direct numpy compat issues in alphalens, we probably don't need a dense testing matrix of all pandas and numpy versions.

**Comment by twiecki** [comment]
Agreed, not sure we're even using any numpy functionality directly.

**Comment by luca-s** [comment]
Very limited use of numpy:

```
alphalens/performance.py:443:                return ((np.nansum(ret) + 1)**(1. / period)) - 1
alphalens/performance.py:621:        / np.sqrt(group_stats.T.xs('count', level=1).T)
alphalens/performance.py:665:    joint_std_err = np.sqrt(std1**2 + std2**2)
alphalens/plotting.py:213:        ax = np.asarray([ax]).flatten()
alphalens/plotting.py:367:        ymin = (np.nanpercentile(mean_ret_by_q.values,
alphalens/plotting.py:369:        ymax = (np.nanpercentile(mean_ret_by_q.values,
alphalens/plotting.py:436:        ymin = (np.nanpercentile(return_by_q.values,
alphalens/plotting.py:438:        ymax = (np.nanpercentile(return_by_q.values,
alphalens/plotting.py:547:    ylim = np.nanpercentile(abs(mean_returns_spread_bps.values), 95)
alphalens/plotting.py:787:           yticks=np.linspace(ymin, ymax, 5),
alphalens/plotting.py:826:    palette = [cm.RdYlGn_r(i) for i in np.linspace(0, 1, quantiles)]
alphalens/utils.py:719:    return period_std / np.sqrt(conversion_factor)
```

**Comment by twiecki** [comment]
Yeah we don't need to version-test for that.

**Comment by luca-s** [comment]
Closing this for now then. We'll see in the future if we need to include numpy in the test matrix.
