### ISSUE TITLE
sector_plots is not a kwarg in create_factor_tear_sheet() 

### ISSUE THREAD

**Issue by kynelee** [quantopian/alphalens#90]
The docs say that sector_plots is a kwarg in create_factor_tear_sheet()
http://quantopian.github.io/alphalens/alphalens.html#alphalens.tears.create_factor_tear_sheet

However, show_sector_plots is the correct kwarg now.

**Comment by jameschristopher** [comment]
fixed https://github.com/quantopian/alphalens/pull/130
