### ISSUE TITLE
Analysis is always performed on 1-day returns even if it's not included in `days` argument.

### ISSUE THREAD

**Issue by jmccorriston** [quantopian/alphalens#92]
![image](https://cloud.githubusercontent.com/assets/4500507/18799523/00738970-81a6-11e6-9b06-a0bf27a7c667.png)

Can be replicated in [this notebook](https://www.quantopian.com/posts/alphalens-a-new-tool-for-analyzing-alpha-factors).

**Comment by twiecki** [comment]
Yes, we explicitly added that for some reason. It doesn't work otherwise. @jameschristopher?

**Comment by jameschristopher** [comment]
This is being talked about in this thread https://github.com/quantopian/alphalens/issues/64
