### ISSUE TITLE
Cannot install alphalens via pip

### ISSUE THREAD

**Issue by ryanyuan42** [quantopian/alphalens#95]
When I use pip to install alphalens, it shows 

  Could not find a version that satisfies the requirement alphalens (from versions: )
No matching distribution found for alphalens

**Comment by jameschristopher** [comment]
We'll be packaging a version 0.1 release in the next few weeks. It will be available on PyPi then.

**Comment by jameschristopher** [comment]
See https://github.com/quantopian/alphalens/issues/29
