### ISSUE TITLE
Hard coded Y axis range in "Forward Return Information Coefficient (IC)" plot

### ISSUE THREAD

**Issue by luca-s** [quantopian/alphalens#99]
[This](https://github.com/quantopian/alphalens/blob/master/alphalens/plotting.py#L206) hard coded range (-0.25, 0.25) can be annoying sometimes.

**Comment by jameschristopher** [comment]
We could hard code a new range  to (-1, 1)

**Comment by luca-s** [comment]
Yes or don't hard code anything and let the plot to auto adjusts the axis ranges by itself. But there might be a  reason behind those hard coded values ?

**Comment by jameschristopher** [comment]
My main reasoning was so that you'd be able to visually compare between multiple graphs. If the axes are different that becomes much harder

**Comment by luca-s** [comment]
That's actually a good reason. So hard coding the range (-1,1) is the way to go...or we could get the maximum Y axis range amongst all the plots and subsequently set that as Y range for all the plots.

**Comment by jameschristopher** [comment]
Andrew and I had talked about doing a max/min range. Sounds good! Fixed in #100
